### ISSUE TITLE
Working example - CosmosDB

### ISSUE THREAD

**Issue by candidson** [ExRam/ExRam.Gremlinq#1]
Hi @danielcweber,

could you please post a small working example for cosmos db?
I have something like this, which however doesn't work. The last command (query.Execute();) throws an Exception ("Method not supported"). However, without it, the cosmos db still is empty. Seems like no query is sent.

`
var cosmosServer = new CosmosDbGremlinServer(hostname, port, enableSsl, dbName, graphName, authKey);
`

`
var qprovider = new ClientGremlinQueryProvider(cosmosServer);
`

`
var query = g
                    .SetQueryProvider(qprovider)
                    .AddV(new Person
                    {
                        Id = new Guid(),
                        Name = "Peter",
                        Age = 36,
                        Profession = "Teacher"
                    })
;
`

`
query.Execute();
`

**Comment by danielcweber** [comment]
I will release a big update shortly that allows for a lower ceremony setup. It'll include minimal working examples for CosmosDB and plain WebSockets.

**Comment by candidson** [comment]
Thanks a lot... That'd be very helpful. Do you have an ETA on the release?

**Comment by danielcweber** [comment]
A preview should be available next week.

**Comment by candidson** [comment]
That's great news.. and really greag job on the project. 
I was wondering though if you could if you could point me in the correct direction with the code snippet above, before the release of the newer version. Basically, my issue isn't really related to Cosmos Db. I would just like to connect to Gremlin Server, and send a few queries.. the examples on the Readme page do not feature the connections to the server as well as the fact of sending/executing the request. That would already be of great help, before the major update next week. Thanks!

**Comment by candidson** [comment]
Thanks @danielcweber... The example works perfectly fine for now- Thousand thanks!!!!!

I have another question though. Does your mapper support nested object? Let's say, that the "Person" object contains a "Profession" object.

The query would look like this:

`
var query = g
                .SetQueryProvider(qprovider)
                .AddV(new Person {
                    Id = Guid.NewGuid().ToString("N"),
                    Name = "Peter",
                    Age = 36,
                    Profession = new Profession
                    {
                        Name = "Teacher",
                        Place = "Berlin"
                    }
                })
                ;
`

Would I need to create a "Profession" separately? Or is there another way? Thanks a lot!

**Comment by danielcweber** [comment]
This is not supported by any Tinkerpop-enabled graph database IMO. Vertex properties can have meta properties (which ExRam.Gremlinq supports!), but the actual values are never nested complex objects.

**Comment by candidson** [comment]
Thanks for the input! 
Will be waiting for the major update next week.. But up until then, will be working with your input. Thanks a lot

**Comment by danielcweber** [comment]
A preview of version 6.0.0 has been released along with a [minimal sample project](https://github.com/ExRam/ExRam.Gremlinq.Samples). Setting up queries for CosmosDb is now much easier. The samples don't show too much of what is possible though, if you happen to play around with ExRam.Gremlinq and want to add some of your queries to the sample project - PRs are very welcome.

**Comment by candidson** [comment]
Thanks a lot. I will be looking into that. Thanks for the great work!
