### ISSUE TITLE
Array injected in first As block becomes empty in second As block. 

### ISSUE THREAD

**Issue by iAmBipinPaul** [ExRam/ExRam.Gremlinq#101]
Hi, Let say I have Vertex `(People)` on which I have ZipCode as one property, I have Edge `(Know)`.
Now I want to get all the People who I do not know and  but comes under array of ZipCode.

```csharp

  public class People :  IVertex
    {
        public string ZipCode { get; set; }
        public string Id { get; set; }
        public string Label { get; set; }
    }

var nearByZipCodes= new string[] {"10001","10199", "10121"};
var userId="";

 await _g.Inject(nearByZipCodes)
                  .Fold()
                   .As((_, injectedNearByZipCode) => _
                   .V<People>(userId).Both<Know>()
                     .OfType<People>()
                      .Values(c=>c.Id).Fold()
                       .As((__, knownPeople) => __
                         .V<People>().Where(c =>
                          !knownPeople.Value.Contains(c.Id) && injectedNearByZipCode.Value.Contains(c.ZipCode)))
                        );
```
I tried the above query but `injectedNearByZipCode` is empty  in the second `As` block.
is this expected  behavior , if yes what will be proper way to write this query.

Thank you !

Version : 
```xml
<PackageReference Include="ExRam.Gremlinq.Providers.CosmosDb" Version="8.0.0-preview-0294" />
```

**Comment by danielcweber** [comment]
What do you mean by 'injectedNearByZipCode is empty'?  How do you determine that? Note that you cannot just debug into the value of `injectedNearByZipCode` and expect there to actually be any contents. It will never contain anything. It's just a step label. There's no code executed on the client side but only on the server side.

Also, there has been a newer preview version for a some time now, please update.

**Comment by iAmBipinPaul** [comment]
Hi ,@danielcweber 
to determine what is the actual value of  `injectedNearByZipCode` I'm adding another `As` Block to select both injectedNearByZipCode and `knownPeople`  and I see that is empty `knownPeople` has some value but `injectedNearByZipCode` is an empty array.

I will prepare one reproducible example and I will update the details here.
Thank you !

**Comment by danielcweber** [comment]
As I said: StepLabels will never have actual values on the client side. It's all on the server side. You won't ever observe the `injectedNearByZipCode` variable to contain actual elements.

**Comment by iAmBipinPaul** [comment]
Okay, I will update the packages if that will resolve problem  it will be awesome.
Otherwise I will prepare one sample reproducible  project.

Thank you for the quick response !

**Comment by iAmBipinPaul** [comment]
Hi , @danielcweber 

I tried this below query on Gremlin server , It's throwing exception.


```
Error executing Gremlin query with RequestId 6c1782d6-1d3a-4315-abbc-f7565895c28d: Gremlin.Net.Driver.Exceptions.ResponseException: ServerError: Neither the sideEffects, map, nor path has a l1-key: WherePredicateStep(within([l1]))
         at Gremlin.Net.Driver.Messages.ResponseStatusExtensions.ThrowIfStatusIndicatesError(ResponseStatus status)
         at Gremlin.Net.Driver.Connection.TryParseResponseMessage(ResponseMessage`1 receivedMsg)
         at Gremlin.Net.Driver.Connection.Parse(Byte[] received)
      --- End of stack trace from previous location where exception was thrown ---
         at Gremlin.Net.Driver.ProxyConnection.SubmitAsync[T](RequestMessage requestMessage)
         at Gremlin.Net.Driver.GremlinClient.SubmitAsync[T](RequestMessage requestMessage)
         at ExRam.Gremlinq.Core.GremlinQueryEnvironmentExtensions.WebSocketGremlinQueryExecutor.<>c__DisplayClass5_0.<<Execute>g__Core|0>d.MoveNext() in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Providers.WebSocket/Extensions/GremlinQueryEnvironmentExtensions.cs:line 72

```

```csharp
 var personWhoMarkDoesNotKnowAndBelongsToNearbyZipCode = await _g
                .Inject(nearByZipCodes)
                .Fold()
                .As((_, injectedNearByZipCode) => _
                    .V<Person>(_marko.Id)
                    .Both<Knows>() 
                    .OfType<Person>()
                    .Fold()
                    .As((__, knownPeople) => __
                        .V<Person>().Where(c =>
                            !knownPeople.Value.Contains(c) && injectedNearByZipCode.Value.Contains(c.ZipCode)))
                );
```

Here is the sample repo 
https://github.com/iAmBipinPaul/ExRam.Gremlinq.issue.101

Thank you !

**Comment by danielcweber** [comment]
Beware of that caveat! Fold steps will erase your path history, including all the step labels. See [here](http://tinkerpop.apache.org/docs/3.2.8/reference/#a-note-on-barrier-steps) for more details on ReducingBarrierSteps. You have to keep that in mind, there's no way Gremlinq can detect these (or is there?). A workaround is to wrap the right part of the query in a map operation:

```
var personWhoMarkDoesNotKnowAndBelongsToNearbyZipCode = await _g
    .Inject(nearByZipCodes)
    .Fold()
    .As((_, injectedNearByZipCode) => _
        .Map(__ => __
            .V<Person>(_marko.Id)
            .Both<Knows>()
            .OfType<Person>()
            .Fold())
        .As((__, knownPeople) => __
            .V<Person>()
            .Where(c => !knownPeople.Value.Contains(c) && injectedNearByZipCode.Value.Contains(c.ZipCode))));

**Comment by iAmBipinPaul** [comment]
Hi , @danielcweber 
Thank you, it works.
I will go through the link you have provided.
