### ISSUE TITLE
Implement Within expression

### ISSUE THREAD

**Issue by ederflo** [ExRam/ExRam.Gremlinq#102]
I would like to get all vertices with a specific property given in a list.

Example:
List<string> names = new List....
await _g.V().Where(x => names.Contains(x.name)).ToArrayAsync();

**Comment by danielcweber** [comment]
What doesn't work about this?

**Comment by ederflo** [comment]
It says, that .Contains is not implemeted.

It is a list and you check if the property of the vertece is in the list.
And in you sample project, you show how to check if a property is in a list of the vertece.#

Your sample: 
var personWithThatPhoneNumber = await _g
        .V<Person>()
        .Where(person => person
            .PhoneNumbers
            .Contains("+491234567"))
        .FirstOrDefaultAsync();

But I want to check, if a property of any vertece is in a given list.

**Comment by danielcweber** [comment]
I guess I'll need a repro project (as asked for in the issue template).

**Comment by ederflo** [comment]
I leaved an example, because it is just two lines long. And i explained it,

List names = new List....
await _g.V().Where(x => names.Contains(x.name)).ToArrayAsync();

Here is the errormassage:
The expression 'value(ARDUVIWeb.Controllers.TruckRoutingController+<>c__DisplayClass10_0).projectIds.Contains(x.ItemId)' is not supported.

**Comment by danielcweber** [comment]
The fact that the code `await _g.V().Where(x => names.Contains(x.name)).ToArrayAsync();` doesn't match the error message `'value(ARDUVIWeb.Controllers.TruckRoutingController+<>c__DisplayClass10_0).projectIds.Contains(x.ItemId)' is not supported` at all justifies my request for a repro.


Look, it's as always. You can't be bothered to put in the effort, but expect me to. That might be the current state of open source but that doesn't mean it's ok.

I have an idea of what might be the shortcoming of ExRam.Gremlinq here, and it is also in my interest to make the scenario you presented possible. If it becomes possible, I will post it here.

**Comment by danielcweber** [comment]
This is fixed on a current preview version on this project's Github packages feed (not Nuget.org!).
