### ISSUE TITLE
GraphBinary support for Janus?

### ISSUE THREAD

**Issue by shaunco** [ExRam/ExRam.Gremlinq#104]
Now that Janus [supports Graph Binary](https://github.com/JanusGraph/janusgraph/pull/2061), it would be fantastic to have Graph Binary support in ExRam.Gremlinq. Graph Binary is quite a bit faster for serialization and deserialization and is much smaller on the wire.

That said, it isn't totally clear to be where ExRam.Gremlinq and Gremlin.Net starts, but Tinkerpop's Gremlin.Net does not yet have support for Graph Binary (only the Java based Gremlin.Core has support).

**Comment by danielcweber** [comment]
Agreed. GraphBinary would be awesome but my focus is mostly on CosmosDB (which doesn't even support Bytecode yet) so unless a PR or serious financial contribution comes along, this has to wait.

**Comment by shaunco** [comment]
Understood. If I can find some cycles I'll try to make a PR.
