### ISSUE TITLE
Constant Step with Boolean Should Output Lowercase for Cosmos

### ISSUE THREAD

**Issue by n-ate** [ExRam/ExRam.Gremlinq#1068]
**Describe the bug**

The constant step with any boolean value seems to always resolve to uppercase `True` or `False`. 

**Expected behavior**
Cosmos expects lowercase `true` or `false` for boolean constants. 

**Version information**
v11.1

**Minimal working example**

C# Gremlinq:
    `g.V().Limit(1).Constant(true);`

Actual Output:  
    `g.V().limit(1).constant(True)`
    
Cosmos Error: 
    `Unable to resolve symbol 'True' in the current context.`
    
Expected Output:
     `g.V().limit(1).constant(true)`
     
     

**Work Around**
C# Gremlinq:
    `g.V().Limit(1).Constant(1);`
    
Then evaluate the response:
`var result = response == 1;`

**Comment by danielcweber** [comment]
As commented above, I'd like to comprehend how you get to the output `g.V().limit(1).constant(True)`. I'd like to see the code that produces this.

**Comment by danielcweber** [comment]
Closing due to lack of feedback by OP and impossibility to reproduce on my side.
