### ISSUE TITLE
Trying to use generics

### ISSUE THREAD

**Issue by LoungeFlyZ** [ExRam/ExRam.Gremlinq#107]
I am new to ExRam.Gremlinq so excuse me if this is  a n00b question.  However, I am trying to build some generic methods for some common things I want to do like add vertex like this:

```
public static async Task<T> UpsertVertex<T>(IGremlinQuerySource g, T vertex, Func<T, bool> comparison)
{
    return await g
        .V<T>()
        .Coalesce(
            (q) => q.V<T>().Where(x => comparison(x)),
            (q) => q.AddV<T>(vertex)
        ).FirstAsync();
}
```
I would like to call it like this:
`var person = await GremlinHelper.UpsertVertex<Person>(_g, personA, (p) => p.Email == personA.Email);`

It compiles, however at runtime I get:
```
Exception thrown: 'ExRam.Gremlinq.Core.ExpressionNotSupportedException' in ExRam.Gremlinq.Core.dll
```

Should this work? Is there another way to achieve the same that is supported?

Thanks.

**Comment by danielcweber** [comment]
`.Where(x => comparison(x))` won't work because `Where` is never called and executed, but the parameter to `Where` is an expression. Thus, it's impossible to pass in arbitrary functions. If you change the type of `comparison` an expression, and pass it in like `Where(comparison)`, you should be good.

**Comment by LoungeFlyZ** [comment]
@danielcweber thanks. I modified it to this and it seems to be working as expected.

```
public static async Task<V> UpsertVertex<V>(IGremlinQuerySource g, V vertex, Expression<Func<V, bool>> equalityExpression) where V : Vertex
{
    return await g
        .V()
        .Coalesce(
            (q) => q.V<V>().Where(equalityExpression),
            (q) => q.AddV<V>(vertex)
        ).FirstAsync();
}
```
```
var person = await GremlinHelper.UpsertVertex<Person>(_g, person1, (p => p.Email == person1.Email ));
```

Thanks for making this library.  I'm completely new to gremlin, so figuring out how to query is a painful still, but I enjoy having the linq'yness that Gremlinq brings.

Out of interest, is there a way to make it log the queries it issues along the the variables for thing like `_a`, `_b` etc...?

**Comment by LoungeFlyZ** [comment]
also ... is this the right place to ask questions about how to use this library? or do you prefer something like stackoverflow @danielcweber ?

**Comment by danielcweber** [comment]
@LoungeFlyZ The samples give [some insight on how to setup logging](https://github.com/ExRam/ExRam.Gremlinq.Samples/blob/main/ExRam.Gremlinq.Samples/Program.cs#L31). You'll need to [tweak the log level though.](https://github.com/ExRam/ExRam.Gremlinq.Samples/blob/main/ExRam.Gremlinq.Samples/Program.cs#L50).

This repo is currently the place where questions are usually asked, StackOverflow not so much. I will try to answer to issues/bugs/etc. as much as time permits.
