### ISSUE TITLE
CosmosDB: Cannot add a vertex where the partition key property has value 'null'.

### ISSUE THREAD

**Issue by devlinse** [ExRam/ExRam.Gremlinq#110]
Hi,

I'm sure this is dead simple to solve, but I've got a simple query that creates a vertex in Gremlin that's throwing up the above message.  When I've manually added things into Cosmos before, I've had to explicitly include the partition key value, but I don't know how to go about doing that with ExRam?

Thanks

**Comment by danielcweber** [comment]
Check out the [Gremlin samples](https://github.com/ExRam/ExRam.Gremlinq.Samples), specifically how a [PartitionKey-property is part of the vertex base class](https://github.com/ExRam/ExRam.Gremlinq.Samples/blob/main/ExRam.Gremlinq.Samples/Model/Vertex.cs#L9) and [how it's excluded from updates to the vertex](https://github.com/ExRam/ExRam.Gremlinq.Samples/blob/main/ExRam.Gremlinq.Samples/Program.cs#L44).

Hope it helps

**Comment by sjwoodard** [comment]
I got this working by specifying the key AND the value in the vertex.
```
    public class Vertex :  IVertex
    {
        public object Id { get; set; }
        public string Label { get; set; }
        public string PartitionKey { get; set; } = "pk";
        public string pk { get; set; };
    }
```
```
            var marko = await _g
                .AddV(new Person { Name = "Marko", Age = 29, pk = "123" })
                .FirstAsync();
```
