### ISSUE TITLE
Path step support

### ISSUE THREAD

**Issue by arnaudvh** [ExRam/ExRam.Gremlinq#113]
SimplePath and CyclicPath steps are implemented but not the Path step: [Apache Tinkerpop Path documentation](https://tinkerpop.apache.org/docs/current/reference/#path-step)

I will need this step for one my projects.

Is it foreseen ?
Could it be possible to return a Path structure (with every vertex/edge that have been traversed) ?

Thank you

**Comment by danielcweber** [comment]
It's currently not on the roadmap and I would have to get an idea of what the signature of such a method would have to look like. Suggestions and contributions are welcome!
