### ISSUE TITLE
.unfold().group().by(keys).by(select(values))

### ISSUE THREAD

**Issue by jonathaneckman** [ExRam/ExRam.Gremlinq#117]
**Describe the solution you'd like**
I am able to run the following query in the gremlin console:

```
g.V('5ee71f40-b40e-43ba-b1a3-adac688c371f')
                .union(
                    project('createdby', 'createdbyid')
                        .by('email')
                        .by('id'),
                    __.in('createdby')
                        .has('id','74e4c1f4-7bd6-4353-ba94-938077551d1a')
                        .project('id', 'name', 'method', 'background')
                            .by('id')
                            .by('name')
                            .by('method')
                            .by('background')
                )
                .unfold()
                .group()
                    .by(keys)
                    .by(select(values)
```

But am having trouble writing it in Gremlinq, specifically around the last 4 methods:

```
.unfold()
       .group()
              .by(keys)
              .by(select(values)
```

I cannot tell if there is a way in Gremlinq to select `keys` for the first `by` and `values to the second `by select`. This is what I have tried so far...

```
var recipesArray = await _graphContext
                .V<User>(currentUserId)
                .Union(
                    __ => __.Project(__ => __
                        .ToDynamic()
                        .By(nameof(TestUserDto.CreatedBy), user => user.Email)
                        .By(nameof(TestUserDto.CreatedById), user => user.Id)
                    ),
                    __ => __.In<CreatedBy>()
                    .V<Recipe>()
                    .Project(__ => __
                        .ToDynamic()
                        .By(nameof(TestUserDto.Name), recipe => recipe.Name)
                    )
                )
                .Group(g => g
                    .ByKey(__ => __)           // Does not work
                    .ByValue(__ => __)
                )
                .Cast<TestUserDto>()
                .ToArrayAsync();
```

**Describe alternatives you've considered**
If its not possible to do with Gremlinq I would fall back to Gremlin.NET. Ideally, Gremlinq exposes the Gremlin.NET client to us so I dont have to configure it twice in my app. Is this already possible?

**Consider sponsoring me**
Sponsored! Thanks for building Gremlinq!

**Comment by danielcweber** [comment]
Hi @jonathaneckman 

thanks for your sponsoring. The presented case is, as of v8.0.0, indeed impossible because there is no equivalent for representing Column-Enums ('keys' and 'values') in ExRam.Gremlinq. Also, it is not immediately clear to me how they could fit in the fluent API...it should be something on the interface you get after Project(...) I guess. Would you be able to rework your example to the bare minimum (in Gremlin and Gremlinq, just pretend there's a syntax ;-)) and give the expected results?

**Comment by danielcweber** [comment]
Also, I am wondering how the Gremlin you wrote up is valid Gremlin, because I can't find an overload for by(...) that takes a Column. Am I misssing something? https://tinkerpop.apache.org/javadocs/current/full/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.html#by--

**Comment by jonathaneckman** [comment]
Your right. I see `select(Column column)` in the docs but nothing for by. In gremlin console, the query in my OP does work though. For what its worth, this was the source of inspiration for using that technique in my query:

https://stackoverflow.com/questions/59308523/gremlin-how-to-flatten-grouped-output
https://stackoverflow.com/questions/60307292/merging-maps-in-gremlin

This is the closest thing I could find to official docs: http://tinkerpop.apache.org/docs/current/recipes/#collections

I cant deep link to the exact spot, so Ctrl + F and look at the groovy example above the paragraph beginning with:

> The code above, basically deconstructs then reconstructs the Map. The key to the pattern is to first unfold() the Map into its key and value entries.

I'm not hip on Linq query syntax to know what would be the best approach, but perhaps it could be done with an overload to `By` and `Select` that accepts an enum/constant from Gremliq instead of a function?

```
.Group(g => g
     .By(Gremlinq.Column.Keys)           
     .By(__ => __.Select(Gremlinq.Column.Values))
 )
```

I have pivoted to letting Gremliq give me a tuple and just map it to a list of classes in my code, so I have a solution for my use case.
