### ISSUE TITLE
Datetime serialization  Changes 8.0.0-preview-0294 to 8.0.0

### ISSUE THREAD

**Issue by iAmBipinPaul** [ExRam/ExRam.Gremlinq#119]
Hi , I'm currently using version `8.0.0-preview-0294` which store `DateTime` as `string` property in `Cosmos DB` like 
`2020-08-19T08:57:13.6677815Z`

After updating to version 8.0.0  , I see it store `DateTime` as `number` property  like 
`1609893960000`

Due to which query condition which is based on `DateTime` is not working.

is there any way that we can keep the `DateTime` as it was before or It is recommended to update the data  like it stores in version `8.0.0`

I think changes is part of this commit.

https://github.com/ExRam/ExRam.Gremlinq/commit/1a33715931c7e920a974496175f73dee1c50629c#diff-c7e4adbe795161d0e63c13049458da900d705ad84149483971d83f9f6b264649R291

Thank you !

**Comment by danielcweber** [comment]
It's an inherent consequence of how timestamps and dates are represented in GraphSON, and the actual conversion is done by the underlying Gremlin.Net library. The change you pointed out made sure that a DateTime will be store just like a DateTimeOffset.

There's probably a workaround for this, but it is of course highly recommended to use the latest format if you're early enough in your development. It won't be changed now that there's a stable version of Gremlinq 8.

**Comment by iAmBipinPaul** [comment]
Hi , Thank you for the quick response. I appreciate all the work you are doing on this library. It will be much better If we will have change log for the version so that it will helps to migrate to the next version. I  do not see any change log in release section.

**Comment by danielcweber** [comment]
I unfortunately don't have the resources to to changelogs for changes in preview-versions. The semantic version with a *preview suffix already gives a hint that things will break without further notice. I agree that more of everything would be awesome. Docs, support, etc. This ist the current state of open source.

I recently got a sponsorship from what I think is your company. Thanks a lot. Leading by good example!

**Comment by iAmBipinPaul** [comment]
Touched my heart

> I agree that more of everything would be awesome. Docs, support, etc. This is the current state of open source.

yes

> I recently got a sponsorship from what I think is your company. Thanks a lot. Leading by good example!

Let's hope , over time it will get better. 

Thank you !
