### ISSUE TITLE
Create multiple edges in a single query

### ISSUE THREAD

**Issue by vmeln** [ExRam/ExRam.Gremlinq#133]
I played with the sample and tried to create multiple edges in a single query with the following code:
```
var markoAndJosh = new[] { _marko.Id!, _josh.Id! };

await _g
    .V(charlie.Id!)
    .AddE<Knows>()
    .To(__ => __
        .V<Person>().Where(x => markoAndJosh.Contains(x.Id)))
    .FirstAsync();
```
However, I see only a single edge was created between Marko and Charlie nodes. 
I know this can be accomplished with a loop, but is it really an issue or I did something wrong? 
Also, thanks for this awesome library 👍

**Comment by danielcweber** [comment]
That's not how addE(...).to(...) works in Gremlin. addE will, for every source vertex, only ever create one edge to the first vertex it encounters in to().

You want

```csharp
await _g
    .V(_marko.Id!, _josh.Id!)
    .AddE<Knows>()
    .To(__ => __
        .V<Person>(charlie.Id))
    .FirstAsync();
```

Here's an introduction to Gremlin: https://tinkerpop.apache.org/docs/current/reference/

**Comment by vmeln** [comment]
That works, thanks for the clarification.
