### ISSUE TITLE
Sample code fails with Cosmos DB

### ISSUE THREAD

**Issue by neildonkin** [ExRam/ExRam.Gremlinq#141]
I have executed your sample code against a Cosmos DB consumption plan graph database.  All of the sample code works except for `Set_and_get_metadata_on_Marko`, which fails with this error message:

`Gremlin Query Execution Error: The graph collection is in the SimpleVertexProperty mode. The property Creator cannot be added/updated with meta properties.`

**Comment by balajichekka** [comment]
Hi,
I am getting same error from samples.
https://github.com/ExRam/ExRam.Gremlinq.Samples

I am using Azure cosmosdb.
attached screenshots


Error:
_fail: Queries[0]
      Error executing Gremlin query with RequestId 134b70a3-72df-48c2-8b7e-9c1f4f27c1ff: Gremlin.Net.Driver.Exceptions.ResponseException: ServerEvaluationError:

ActivityId : e7a55cf9-464d-4135-9f9a-aa3d4b51b730
ExceptionType : GraphRuntimeException
ExceptionMessage :
        Gremlin Query Execution Error: **The graph collection is in the SimpleVertexProperty mode. The property Creator cannot be added/updated with meta properties.**
        GremlinRequestId : 134b70a3-72df-48c2-8b7e-9c1f4f27c1ff
        Context : graphcompute
        Scope : graphcomp-execquery
        GraphInterOpStatusCode : GraphRuntimeError
        HResult : 0x80131500_

         at Gremlin.Net.Driver.Messages.ResponseStatusExtensions.ThrowIfStatusIndicatesError(ResponseStatus status)
         at Gremlin.Net.Driver.Connection.HandleReceivedMessage(ResponseMessage`1 receivedMsg)
         at Gremlin.Net.Driver.Connection.HandleReceivedAsync(Byte[] received)
         at Gremlin.Net.Driver.ProxyConnection.SubmitAsync[T]
[Doc1cosmosDBerrors.docx](https://github.com/ExRam/ExRam.Gremlinq/files/8209113/Doc1cosmosDBerrors.docx)

**Comment by balajichekka** [comment]
> Hi, I am getting same error from samples. https://github.com/ExRam/ExRam.Gremlinq.Samples
> 
> I am using Azure cosmosdb. attached screenshots
> 
> Error:
> 
> ```
> _fail: Queries[0]
>       Error executing Gremlin query with RequestId 134b70a3-72df-48c2-8b7e-9c1f4f27c1ff: Gremlin.Net.Driver.Exceptions.ResponseException: ServerEvaluationError:
> 
> ActivityId : e7a55cf9-4135-9f9a-aa3d4b51b730
> ExceptionType : GraphRuntimeException
> ExceptionMessage :
>         Gremlin Query Execution Error: **The graph collection is in the SimpleVertexProperty mode. The property Creator cannot be added/updated with meta properties.**
>         GremlinRequestId : 134b70a3-72df-8b7e-9c1f4f27c1ff
>         Context : graphcompute
>         Scope : graphcomp-execquery
>         GraphInterOpStatusCode : GraphRuntimeError
>         HResult : 0x80131500_
> 
>          at Gremlin.Net.Driver.Messages.ResponseStatusExtensions.ThrowIfStatusIndicatesError(ResponseStatus status)
>          at Gremlin.Net.Driver.Connection.HandleReceivedMessage(ResponseMessage`1 receivedMsg)
>          at Gremlin.Net.Driver.Connection.HandleReceivedAsync(Byte[] received)
>          at Gremlin.Net.Driver.ProxyConnection.SubmitAsync[T]
> ```
> 
> [Doc1cosmosDBerrors.docx](https://github.com/ExRam/ExRam.Gremlinq/files/8209113/Doc1cosmosDBerrors.docx)

@danielcweber Please check

**Comment by danielcweber** [comment]
Can't reproduce. Don't know which query is really failing. Don't have a full stack trace. Asked twice now for a minimal (not) working repro repo. That's all I can do for now.

**Comment by balajichekka** [comment]
> Can't reproduce. Don't know which query is really failing. Don't have a full stack trace. Asked twice now for a minimal (not) working repro repo. That's all I can do for now.
> 
> EDIT: Sorry for confusing the OP with @balajichekka.

Attaching stack trace,  code is exact same , nothing changed except azure connection string.
Thanks for checking..
[stacktrace.docx](https://github.com/ExRam/ExRam.Gremlinq/files/8234879/stacktrace.docx)
.
