### ISSUE TITLE
Coalesce with Constant

### ISSUE THREAD

**Issue by BlaszczykB** [ExRam/ExRam.Gremlinq#149]
Hi,
I have a problem with projecting connected vertexes. I would like to receive Tuple that contains information regarding 'Team' and 'Stadium' so this is the query that i'm currently working on :

```
Gremlin
  .V<Team>()
  .Project(t => t
    .ToTuple()
    .By(t => t.Cast<Team>())
    .By(__ =>
    {
	return __.Cast<Stadium>().In<PlaysOn>().OfType<Stadium>()
    }));
```

This works fine when there is data for both Team and Stadium. Problem is when there is no corresponding data for Stadium. I am receiving this information:
> Gremlin Query Execution Error: Project By: Next: The provided traverser of key "Item2" maps to nothing.

I thought that in case  when there is no corresponding 'Stadium', constant of null could help, but i am not able build write 'Coalesce' with 'Constant'. Here is how i would imagine it (code not compiling) :

```
Gremlin
  .V<Team>()
  .Project(t => t
    .ToTuple()
    .By(t => t.Cast<Team>())
    .By(__ =>
    {
	return __.In<PlaysOn>().OfType<Stadium>().Fold().Coalesce(
	  _ => _.Unfold(),
	  _ => _.Constant<Stadium>(null));
    }));

```

Here is the query that works on gremlin

```
g.V()
  .hasLabel('Team').as('T')
  .project('team', 'stadium')
    .by(select('T'))
    .by(__.in('PlaysOn').has('label', 'Stadium').fold().coalesce(
	unfold(), constant('No Stadium')))
```

I tried to use Constant in different ways but i was not able to make it work. Could you also give some simple example how this should look like?

**Comment by danielcweber** [comment]
There is no such thing as null in Gremlin, so Constant(null) won't ever work. Constant("No Stadium") will work, however, now your code doesn't compile because there's a type mismatch in Coalesce - one of the subqueries yields Stadiums whereas the other yields strings. Apply `Cast<object>()` to both of them (-> `Unfold().Cast<object>() and Constant(...).Cast<object>()`)  and it'll compile.

Now you got a query of objects (sometimes a Stadium, sometimes a string), which is probably not what you wanted. In this case, you can't do better than to apply a filter before the project - `Where(__ => __.In<PlaysOn>.....)` will only let the teams with a stadium pass. Project will always succeed then.

**Comment by BlaszczykB** [comment]
Problem is that i would like to always have information about 'Team'. 'Stadium' is optional, so this is something like left join.

I tried to use `Cast<object>()` on both of Coalesce options:
```
.By(__ =>
{
  return __.In<PlaysOn>().OfType<Stadium>().Fold().Coalesce(
    _ => _.Unfold().Cast<object>(),
    _ => _.Constant("No Stadium").Cast<object>());
}));
```

But when i do so Coalesce has this information:	

> CS0411	The type arguments for method 'IGremlinQueryBaseRec<IArrayGremlinQuery<Stadium[], Stadium, IVertexGremlinQuery<Stadium>>>.Coalesce<TTargetQuery>(params Func<IArrayGremlinQuery<Stadium[], Stadium, IVertexGremlinQuery<Stadium>>, TTargetQuery>[])' cannot be inferred from the usage. Try specifying the type arguments explicitly.

I know that code below doesn't make sense but in this case everything compiles, so something with 'Constant' is crushing the code:

```
.By(__ =>
{
  return __.In<PlaysOn>().OfType<Stadium>().Fold().Coalesce(
    _ => _.Unfold().Cast<object>(),
    _ => _.Unfold().Cast<object>());
}));
```

**Comment by danielcweber** [comment]
Slip a ForceValue() in before the casts. Currently, one is a IValue... and the other is a IVertex....ForceValue will make the interfaces equal.

Actually, why even do the whole Coalesce-thingy. If you change the view on the domain such that teams may have 0-n stadiums, a single Fold() will do.

**Comment by danielcweber** [comment]
As a rule of thumb, always observe the type of the queries (I....GremlinQuery<...>).

**Comment by BlaszczykB** [comment]
Thank you, both solutions are working
