### ISSUE TITLE
IGremlinQueryBase.Debug() renders CosmosDbKey as String[] insead of values

### ISSUE THREAD

**Issue by utillity** [ExRam/ExRam.Gremlinq#1552]
**Describe the bug**
The string produced by .Debug() is super now, allowing the developer to directly copy/paste the query to the database tool for further debugging. Currently, only the CosmosDbKey is not serialized to string correctly. Instead of showing the actual value, it is serialized as `System.String[]`

ie: `g.V(System.String[]).hasLabel('Article')\n.property(single,'IndexPending',true)\n.property(single,'Timestamp',638493747170715656)\n.property(single,'Trend',0)`

**Expected behavior**
It would be great to see the actual key, as in `g.V(['id', 'key']).hasLabel('Article')\n.property(single,'IndexPending',true)\n.property(single,'Timestamp',638493747170715656)\n.property(single,'Trend',0)`

**Version information**
Using v12.6.0

**Minimal working example**
If you really need this, I would be happy to provide you with some code

**Comment by danielcweber** [comment]
Fixed by #1610
