### ISSUE TITLE
v12 - Array.Empty<T> translates to ObjectName[] instead of json []

### ISSUE THREAD

**Issue by krukowskid** [ExRam/ExRam.Gremlinq#1598]
**Describe the bug**
I am trying to upgrade Gremlinq from 11.2.5 to 12.6.4, however I've run into an issue which I am not sure if it's expected behavior. After migration to v12, all queries that are using `Array.Empty<T>()` started to fail.

```C#
.By(nameof(InvitationDbQueryResponse.Departments), i => i.Coalesce(_ => _.OutE<For>().InV<Department>(),
                                                              _ => _.Constant(Array.Empty<Department>()))))
```

After investigation I have found out that in v12.x it converts `Array.Empty<Department>()` to object name like `Namespace.Department[] `instead of json `[]` which causes query error. Is it some misconfiguration on my side, an issue, or is it by design and the only way to fix it is to modify each query to use `.Fold()`?

**Expected behavior**
It should resolve `_.Constant(Array.Empty<Department>` to `__.constant([])`

**Version information**
11.2.5 -> 12.6.4

**Minimal working example**

```
.AddGremlinq(setup => setup
        .UseCosmosDb<Vertex, Edge>()
        .UseNewtonsoftJson())
```
```
_g.V<Company>(companyId).Project(p => p.ToDynamic().By("objects", i => i.Coalesce(_ => _.Constant(Array.Empty<string>()),
                                                                              _ => _.Constant(Array.Empty<string>()))));
```

**Comment by danielcweber** [comment]
Fixed by #1610
