### ISSUE TITLE
Multiple issues when you have separated classes in different assemblies

### ISSUE THREAD

**Issue by sebastianamaro** [ExRam/ExRam.Gremlinq#1644]
**Describe the bug**
I have a solution which uses GremlinQ. Since I am using a Microservice architecture, I need some common logic between the MS that access the graph, which I put in a shared custom nuget package.
After I did this 2 things started to happen

Only on AddV (not on update), i get an Argument Exception saying my object is not part of the model.
The Path() response, changed, and instead of having the actual objects in the Objects field of the Path object, i has some Newtonsoft Dynamic representation (I dont have an example now, but if you need it I could try to recreate this).

I later found an answer to this, and it was adding 

.ConfigureEnvironment(env=> env.UseModel(GraphModel.FromBaseTypes<Vertex, Edge>().AddAssemblies(typeof(Node).Assembly)));

Where Node is a vertex class that lives in the running assembly, and Vertex, Edge run in another assembly.

But that rises a 3rd issue, that is that the Path() query built is not correct, because it assuming the wrong label from the configured query.

**Expected behavior**
I expect the library to behave consistently whether we have the classes among one or multiple assemblies.

**Version information**
12.7.0

**Minimal working example**
https://github.com/sebastianamaro/Gremlinqissue

**Additional context**

I reported a bit more here: https://github.com/Gremlinq/ExRam.Gremlinq/issues/1627
But since I was not sure if I should open a new issue or not, I made it this way. Feel free to close either one of this.

**Comment by danielcweber** [comment]
Cont'd in #1627.
