### ISSUE TITLE
Default update behaviour changed from version 11 to 12.

### ISSUE THREAD

**Issue by danneforslund** [ExRam/ExRam.Gremlinq#1693]
**Describe the bug**
In version 11 and until 12.0.0-preview.16, performing an update on a vertex would not drop any properties set to null, but rather "patch" the vertex with any non-null properties in the supplied vertex.

```
public class Person {
    public string Id { get; set; }
    public string? Name { get; set; }
    public int? Age { get; set; }
}

await _g.V<Person>("joe").Update(new Person() { Age = 26 }).FirstOrDefaultAsync();

=> g.V("joe").hasLabel("person").property(single,"age",26)
```

In subsequent versions, the same query drops all nullable properties, such as the name property in the example:

```
=> g.V("joe").hasLabel("person").sideEffect(__.properties("name").drop()).property(single,"age",26)
```

**Expected behavior**
I expected this to work as in previous versions to avoid either prefetching the vertex to be updated or manually constructing a chained .Property() query for multiple properties.

**Version information**
12.7.3 with ExRam.Gremlinq.Providers.CosmosDb and ExRam.Gremlinq.Support.NewtonsoftJson

**Comment by danielcweber** [comment]
This is Gremlinq's semantics for updates in v12. The updated object doesn't have the name set, so it is dropped. If it's just about patching the age, an explicit call to `Property` is probably more in order.

**Comment by danneforslund** [comment]
Thank you for the answer Daniel. I thought that was the difference between say Update and ReplaceV. My use case is unfortunately a little more than patching single properties as I have multiple external systems pushing property changes via an API  endpoint (PATCH) to the graph. It was very handy to be able to only send the changed properties to reduce request size and commit them directly using Update().

I'll probably resort to a custom function with reflection to create a chained Property() query with any non-null properties then, should this not be configurable with Gremlinq. 

I'll close this issue for now. Thanks again!

**Comment by danielcweber** [comment]
ReplaceV() is just short for V().Update(...). Have a look whether the relatively new TinkerPop merge-operators would work for you. Although I see you're on CosmosDb so there's no merge.
