### ISSUE TITLE
V() guids array serialization

### ISSUE THREAD

**Issue by aristovg** [ExRam/ExRam.Gremlinq#19]
Hi, 
seems that guids array are not properly serialized in calls to `V(params object[] ids)`

```csharp
        [Fact]
        public void VGuid()
        {
            var strings = new[] { "string1", "string2" };

            g.V(strings).Should().SerializeToGroovy<CosmosDbGroovyGremlinQueryElementVisitor>("g.V(_a, _b)")
                .WithParameters("string1", "string2");

            var guid1 = Guid.NewGuid();
            var guid2 = Guid.NewGuid();

            var guids = new[] {guid1, guid2};

            g.V(guids).Should().SerializeToGroovy<CosmosDbGroovyGremlinQueryElementVisitor>("g.V(_a, _b)")
                .WithParameters(guid1, guid2);
        }
```

Guid serialization ends with a query `g.V(_a)`, and parameter serialized to a complex object that looks like this: 
`{{80263ee2-6e17-4643-af7c-a613bb6254f9}, {5dbc9a0c-a9c1-4d01-afa7-df822f664ec7}}.`

This fails in Azure CosmosDb, probably in other implementations as well.

**Comment by danielcweber** [comment]
It's because you are passing a string array into a method that takes `params object[]`. Thus, the string array will inevitably end up as the first element in an object array. Gremlinq doesn't do any magic here to determine you meant something else. Replace 

    var strings = new[] { "string1", "string2" };

by

    var strings = new object[] { "string1", "string2" };

and you should be fine.

**Comment by danielcweber** [comment]
More technically: Array covariance doesn't work from T[] to object[] when T is a struct.

**Comment by aristovg** [comment]
Yeah, that makes sense. We actually used the `new object[]` approach as a workaround, so I guess it's more of "nice-to-have" feature (maybe a generic constraint of some sort, not sure). 

Thanks anyway, keep up the amazing work.
