### ISSUE TITLE
Retry for Request too large

### ISSUE THREAD

**Issue by Hatzman91** [ExRam/ExRam.Gremlinq#21]
is there a way to use a retry mechanism when i hit the 'request too large' exception?

**Comment by danielcweber** [comment]
I have so far used this extension (C# 8) which you can easily use with `                    .ConfigureExecutionPipeline(_ => _
                        .Retry(logger));` after `UseCosmosDB`:

````
        private sealed class RetryPipeline : IGremlinQueryExecutionPipeline
        {
            private const int MaxTries = 1000;

            private readonly ILogger _logger;
            private readonly IGremlinQueryExecutionPipeline _basePipeline;

            public RetryPipeline(IGremlinQueryExecutionPipeline basePipeline, ILogger logger)
            {
                _logger = logger;
                _basePipeline = basePipeline;
            }

            public async IAsyncEnumerable<TElement> Execute<TElement>(IGremlinQuery<TElement> query)
            {
                var tries = MaxTries;

                while (true)
                {
                    await using (var enumerator = _basePipeline.Execute(query).GetAsyncEnumerator())
                    {
                        var exit = false;

                        while (true)
                        {
                            var hasNext = false;

                            try
                            {
                                hasNext = await enumerator.MoveNextAsync();
                            }
                            catch (ResponseException ex)
                            {
                                _logger.LogWarning(ex, "Retrying gremlin query: ");

                                if (tries-- > 0 && ex.StatusAttributes.TryGetValue("x-ms-status-code").Exists(x => (long)x == 429))
                                {
                                    await Task.Delay(ex.StatusAttributes
                                        .TryGetValue("x-ms-retry-after-ms")
                                        .Bind(x => TimeSpan.TryParse(x.ToString(), out var timeSpan) ? timeSpan : default(Option<TimeSpan>))
                                        .IfNone(TimeSpan.FromMilliseconds(100)));

                                    break;
                                }

                                throw;
                            }

                            if (hasNext)
                                yield return enumerator.Current;
                            else
                                yield break;
                        }
                    }
                }
            }
        }

        public static IGremlinQueryExecutionPipeline Retry(this IGremlinQueryExecutionPipeline pipeline, ILogger logger)
        {
            return new RetryPipeline(pipeline, logger);
        }
    }
````

**Comment by Hatzman91** [comment]
Damn, then i have to wait till Core 3.0 is out of preview (we should not use preview versions for productive applications)

but thanks for that snippet!

**Comment by javaadpatel** [comment]
@Hatzman91 I also can not use c# yet, so I implemented a polly retry policy. I've tested it and it works. This is the policy if you are interested in using it:
```
 private static AsyncRetryPolicy RequestRateRetryPolicy = Policy
        .Handle<ResponseException>(re => re.StatusAttributes.TryGetValue("x-ms-status-code").Exists(x => (long)x == 429) == true)
        .WaitAndRetryAsync(retryCount: 10,
            sleepDurationProvider: (retryAttempt, exception, context) =>
            {
                var defaultRetryAfter = TimeSpan.FromMilliseconds(100);
                if (exception is ResponseException)
                {
                    string responseExceptionRetryAfter = (string)((ResponseException)exception).StatusAttributes["x-ms-retry-after-ms"];
                    var couldParseTimespan = TimeSpan.TryParse(responseExceptionRetryAfter, out defaultRetryAfter);
                    return defaultRetryAfter;
                }
                return defaultRetryAfter;
            },
            onRetryAsync: (exception, timespan, retryAttempt, context) =>
            {
                //do stuff like logging I guess, don't really use this function.
                return Task.CompletedTask;
            }
          );
```

I hope this helps you. I've noticed that although this solves the request rate issue, when the requests are too many then I get this exception, which I am working on figuring out now:
![Exception after retry request exception](https://user-images.githubusercontent.com/22832462/64271618-e85eea80-cf3d-11e9-9f57-e74f34078023.PNG)

**Comment by mouaxiong** [comment]
Is there an updated version of this using the latest sample project code?  I tried the code above and there weren't the same options to wire up the retry pipeline.  Any updates on this would help.  Thanks.

_g = g
                .ConfigureEnvironment(env => env
                    .UseLogger(serviceProvider.GetService<ILoggerFactory>().CreateLogger("logger"))
                )
                
                //Uncomment below, comment above and enter appropriate data to configure Gremlinq to work on CosmosDB!
                .UseCosmosDb(new Uri("wss://" + hostname + ":" + port), database, collection, authKey);
                
                // Use on localhost (ws)
                //.UseCosmosDb(new Uri("ws://" + hostname + ":" + port), database, collection, authKey);

            return _g;

**Comment by danielcweber** [comment]
Use the 'AutoPilot' feature in CosmosDB for peaks in request rate. Other than that, there is nothing to add to the above snippets, which can easily be adopted to the new Gremlinq 8-architecture.

**Comment by mouaxiong** [comment]
Thank you for the comment as that makes sense for now.  I'm pushing data out to azure and using gremlinq and so is there anything you can add in terms of optimizing for performance to make the data inserts faster?  I tried to look in the issues/questions section and didn't find anything.

I am aware of the gremlin bulk library for gremlin.net but I was checking for gremlinq specifically.  Thank you.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by danielcweber** [comment]
> is there anything you can add in terms of optimizing for performance to make the data inserts faster

Of course, [I am always looking to optimize performance](https://github.com/sponsors/danielcweber). Any concrete ideas on how to gain performance?

**Comment by mouaxiong** [comment]
I'm working with a very large data set (over million records potentially).  I'm using gremlinq to push data to build a testable dataset so that I can better gauge the RU usage.  I'd like to use gremlinq since it allows me to check and set appropriate edges and vertices for the relationships.  

I've tried using parallel.foreach to push data but I get an exception indicating that I've exceeded the number of processors.  I was just wondering if you knew of any other better way or more efficient way to push data to the graph database.  Thanks for your input.

**Comment by menth0l** [comment]
Can someone provide a working example for code snipplet in second post? I'm using Gremlinq version 8.0.0 and can't find method ConfigureExecutionPipeline anywhere.

**Comment by danielcweber** [comment]
I don't currently have a working snippet that would implement retry, it's an anti pattern anyway: By retrying you might end up with doubled vertices, inconsistent stuff etc. Instead, it's highly recommended to use the AutoPilot feature of CosmosDB which will provision more RU/s when needed, so larger peak workloads will run smoothly. I've been using it for a while now, it does the trick.
