### ISSUE TITLE
Unable to recreate valid as/select query in Gremlinq

### ISSUE THREAD

**Issue by phleebagg** [ExRam/ExRam.Gremlinq#22]
I have this query:

g.V('someId').hasLabel('Vertex').as('a').in('EdgeName').hasLabel('Vertex').as('a').select('a').unfold().dedup()

I'm able to run it against Gremlin server with no issues, but am unable to recreate the query using the type safe syntax of Gremlinq.

Direct translation:

        var a = new StepLabel<Vertex>();
         _g
                .V<Vertex>()
                .Where(x => x.Id=="someId")
                .As(a)
                .In<EdgeName>()
                .OfType<Vertex>()
                .As(a)
                .Select(a)
                .Unfold()
                .Dedup();

Unfold() is not a valid operation of IGremlinQuery. Have attempted using a other types for the step label (e.g. Vertex[]) and casting to IArrayGremlinQuery, but to no avail (errors at runtime on cast).

Is this type of query possible in Gremlinq, or is more work needed to accommodate it?

**Comment by danielcweber** [comment]
But you can't unfold a vertex anyway, can you? What's the intention of your query?

**Comment by danielcweber** [comment]
Run the query against gremlin server without the unfold. It should yield the exact same results.

**Comment by phleebagg** [comment]
I may be mixing up terminology. So by Gremlin server, I actually meant the Cosmos Gremlin API, and am looking at the JSON being returned.

When I run the query without a fold, I get back an array of arrays of vertices. Each array of vertices contains the initial vertex, and then one of the vertices found along the edge.

 Unfold turns it into a single array of vertices, with duplicates of the initial vertex.

My ultimate goal with the query is to grab the vertex and the vertices linked by an edge (of type "EdgeName") and drop all of them.

**Comment by danielcweber** [comment]
Can you run the query against Gremlin Server? I tested this on CosmosDB and it seems that CosmosDB accumulates the vertices along the path into an array, which is IMO not the correct behaviour. Gremlin Server doesn't accumulate an array.

**Comment by danielcweber** [comment]
The reason the Unfold method is not available at this point in your query is because conceptually, it doesn't make any sense. The fact that CosmosDB shows what I think weird behaviour here doesn't change that. The actual semantics of "as" don't include accumulation. You just label the current element a traverser is on. In both usages of "as" in your query, that is a vertex. Your end result should be an array of vertices. 

Conceptually, you rather want something like this:

g.V('someId').as('a').in().as('b').local(union(select('a'), select('b')).fold())

**Comment by phleebagg** [comment]
I'll go that route, then. I'll have to spend some more time in the Tinkerpop docs! Thanks for your time on this.

**Comment by danielcweber** [comment]
I'm afraid theres quite a few differences in behaviour between the reference Tinkerpop implementation and CosmosDB, and unlike with say .net core and tons of other stuff, Microsoft isn't too open about those issues and their resolution.
