### ISSUE TITLE
Setting Label does not affect the label on the vertex

### ISSUE THREAD

**Issue by javaadpatel** [ExRam/ExRam.Gremlinq#25]
I would like to be able to set the label, and I see that there is a label property, so in the sample project, there is a dog class which ultimately inherits from `Vertex` class. The label gets set to `Dog` which is the class name, I tried doing:
```
   var charlie = await _g
              .AddV(new Dog { Name = "Charlie", Age = 2, Label = "NotDog" })
              .FirstAsync();
```

but this doesn't actually set the label.

The reason i'm trying to do this is that I have a project which imports ExRam.Gremlinq and has a class `Vertex` similar to the one in the sample, but then in another project, I inherit from `Vertex` to create `User` but the label stays Vertex in the graph.

**Comment by danielcweber** [comment]
This is not how setting labels is intended to work. The mapping of labels to classes is determined by the model, which you can set and configure on the GremlinQuerySource. After all, how is Gremlinq supposed to know to query for "NotDog" when you want to say g.V<Dog>()?

**Comment by javaadpatel** [comment]
okay that makes sense, I was just confused because I saw the `Label` property and I thought that was some way to override the className.

so i have set the model to use with this line:
```
.UseModel(GraphModel.FromBaseTypes<Vertex, Edge>())
```

but like I said when I inherit from `Vertex` and my model exists in a different project then the Label stays `Vertex`?

**Comment by danielcweber** [comment]
Doesn't really matter which project Vertex resides in. If Vertex is not abstract and you actually add an 
 instance of Vertex to the graph, then yes, the label is Vertex, though you can play around with casing a little (there's extensions on the graph model).

**Comment by javaadpatel** [comment]
ah amazing, thank you so much, i marked vertex as abstract like :
```
public abstract class Vertex : IVertex
```

then I can keep vertex in a different project and still inherit from it and the label will be set correctly. Thank you for that hint.
