### ISSUE TITLE
Opening up ConnectionPoolSettings in AddWebSocketExecutor method

### ISSUE THREAD

**Issue by javaadpatel** [ExRam/ExRam.Gremlinq#28]
Hi, 
I've been trying some load testing on my graph to check whether I'm modelling my data effectively, and I ran into this exception:
![image](https://user-images.githubusercontent.com/22832462/64287371-c70ef600-cf5f-11e9-9728-c82889f4c2f3.png)

I saw there is a `connectionPoolSetting` that could be exposed in the `AddWebSocketExecutor` method, shown here:
![image](https://user-images.githubusercontent.com/22832462/64287413-f291e080-cf5f-11e9-9d46-4aca947cf90b.png)

Could I make a PR to expose this setting? This would allow users to set their own connection `PoolSize` and `MaxInProcessPerConnection` settings instead of having to use the defaults.

**Comment by danielcweber** [comment]
I wouldn't currently accept such a PR because it would make the abstraction leak. I recognize the issue here though.

**Comment by javaadpatel** [comment]
What is the best way to get around this error? I am now experiencing it in my production environment as the load is too great.

**Comment by javaadpatel** [comment]
I see there's actually a way to pass a `Func<IGremlinClient> clientFactory` to the ` .AddWebSocketExecutor` method and that allows you to control all the settings actually.
