### ISSUE TITLE
Compare by id for unkown vertex types

### ISSUE THREAD

**Issue by vmeln** [ExRam/ExRam.Gremlinq#288]
I know that the library is strongly typed, however, I need to check an `Id` property for equality (I don't care about other fields) while the Vertex type is unknown. Is it possible to make it compile/work?
```
await this.g.V<ContentVertex>(vertexKey).Out<Added>()
    .Where(x => x.Id() == entityKey)
    .SingleOrDefaultAsync();
```

**Comment by vmeln** [comment]
Seems that the cast to base type works without issues. Sorry for bothering you.

**Comment by danielcweber** [comment]
Sorry, this must have slipped through. Yes, casting to the base vertex type is indeed the way to go (since Out(..) will just ever be typed on `object`). So eventually this becomes

```
await this.g.V<ContentVertex>(vertexKey)
    .Out<Added>()
    .Cast<TBaseType>()
    .Where(x => x.Id() == entityKey)
    .SingleOrDefaultAsync();
