### ISSUE TITLE
What is the equivalent of the `Has` step in gremlin query?

### ISSUE THREAD

**Issue by javaadpatel** [ExRam/ExRam.Gremlinq#29]
Hi, I was just wondering what the equivalent of the `has` step is in this library? I would like to write the query:
```
g.V().has('LoginProvider','gmail').inE().has('ProviderKey','userKeyGoogle500').outV()
```

I noticed there is a `Where` step, so I've written my query like this:
```
 var user = await _g.V()
                    .Where(x => x.LoginProvider == loginProvider) 
                    .InE()
                    .Where(x => x.ProviderKey == providerKey)
                    .OutV()
                    .FirstOrDefaultAsync();
``` 
i'm not sure if that translates to `has` underneath before submitting to cosmosdb, or if it actually would come out like:
```
g.V().where(values('LoginProvider').is('loginProvider')).inE().where(values('ProviderKey').is('providerKey')).outV()
```

**Comment by javaadpatel** [comment]
I used the `Profile()` step and saw that there where a number of `Has` steps that where going to be executed, 
![image](https://user-images.githubusercontent.com/22832462/64440100-a9f73600-d0cb-11e9-8bb3-2e8114121f42.png)

so I'm guessing that `Where` translates to `has`

**Comment by danielcweber** [comment]
Yes. Just use Where. It'll do the appropriate thing.
