### ISSUE TITLE
Store/Cap steps?

### ISSUE THREAD

**Issue by phleebagg** [ExRam/ExRam.Gremlinq#30]
It appears that these are not implemented. Is there any plan to add them in or are there big hurdles? 

It would be nice for tracking what if anything was dropped by a query (e.g. store('x').drop().cap('x'))

Edit: If anyone is trying to do something similar to above, it can be accomplished via sideEffect(drop()).

**Comment by danielcweber** [comment]
As so often in open source, the answer is simple: It's not implemented because I didn't need it. I might need it in the future. Also, I am accepting pull requests ;-)

**Comment by danielcweber** [comment]
Closing. It's in the backlog. You know....

**Comment by DocGreenRob** [comment]
@danielcweber is this still in the backlog?
