### ISSUE TITLE
RepeatUntil sample

### ISSUE THREAD

**Issue by smolesen** [ExRam/ExRam.Gremlinq#31]
Could you please add an example on how to use RepeatUntil

Trying to figure out how to use RepeatUntil to run a query like:
````
g.V('c046d201-4999-4fa7-8888-8653dfc11ad6').hasLabel('folder').repeat(inE().outV().simplePath()).until(has('name','Root'))
````
Tired:
````
_g.V<folder>("c046d201-4999-4fa7-8888-8653dfc11ad6").RepeatUntil(__ => __.InE().OutV(), __ => __.V<root>());
````
but it doesn't compile

TIA

**Comment by danielcweber** [comment]
So....what's the compilation error?

**Comment by smolesen** [comment]
Hi Daniel

The error is:
````
'IGremlinQuery<folder>' does not contain a definition for 'InE' and no accessible extension method 'InE' accepting a first argument of type 'IGremlinQuery<folder>' could be found (are you missing a using directive or an assembly reference?)
````
Not really sure what I'm missing....

TIA

/Søren

**Comment by danielcweber** [comment]
Try

`_g.V<folder>("c046d201-4999-4fa7-8888-8653dfc11ad6").Cast<IVertex>().RepeatUntil(__ => __.InE().OutV(), __ => __.V<root>());

**Comment by danielcweber** [comment]
It could automatically resolve to the right signature, but method resolution fails when it can't match the generic type parameter and unfortunately doesn't look any further. The signatures in Gremlinq shall change then.

**Comment by smolesen** [comment]
Your suggestion is working, just have to cast the objects back to T before rerturning:
````
        public async Task<List<T>> SearchParent<T>(Guid id) where T : Vertex
        {
            var ts = await g.V(id).Cast<IVertex>().RepeatUntil(__ => __.InE().OutV(), __ => __.V<T>()).ToListAsync();
            return ts.Cast<T>().ToList();
        }
````
