### ISSUE TITLE
UseLogger ignores supplied logger

### ISSUE THREAD

**Issue by smolesen** [ExRam/ExRam.Gremlinq#32]
Hi

Trying to setup a logger, so I can see the resulting Gremlin query, I've tried:

````
var logger = loggerFactory.CreateLogger("Gremlin");
services.AddSingleton<IConfigurableGremlinQuerySource>(
     x => GremlinQuerySource.g
     .UseLogger(logger)
     .UseModel(GraphModel.FromBaseTypes<Vertex, Edge>())
     .UseCosmosDb("...", "...", "...", "..."));
````
But I don't get any logging. If I look in .UseLogger(), it seems to ignore the supplied logger:
````
IConfigurableGremlinQuerySource IConfigurableGremlinQuerySource.UseLogger(ILogger logger)
{
    var newModel = _isUserSetModel
          ? Model
          : GraphModel.Dynamic(NullLogger.Instance);
````
Shouldn't it be:
````
 GraphModel.Dynamic(logger);
````
Is there another way to setup a logger? 

TIA

/Søren

**Comment by danielcweber** [comment]
Indeed a bug but not one that would lead to you not seeing any logs. With your setup as above, you should be able to see the queries. Please check your configured log level.

**Comment by smolesen** [comment]
Aha yes, it's indeed working... not sure why I couldn't get it to work in the first place... maybe I changed the Filter to LogLevel.Trace as well....
