### ISSUE TITLE
Issue using Project in tandem with Coalesce

### ISSUE THREAD

**Issue by mike-kolback** [ExRam/ExRam.Gremlinq#320]
I'm dealing with a dual-faceted issue and cant seem to find a resolution regarding using projection in tandem with coalesce.  What I'm trying to achieve is a query that always returns the 'Parent Vertex' even if it contains no out edges.  At the same time, if the 'Parent Vertex' contains multiple out edges, I need to return all the 'Child Vertices' in some type of array.

So far I've written this.

```
return await _g
.V(sourceVertex.Id)
.Out()
.OfType<T>()
.Project(b => b
  .ToDynamic()
  .By(parentVert => parentVert)
  .By(
      "childVerts",
      __ => __
          .Cast<U>()
          .Coalesce(
              (q) => q.Out<Contains>().OfType<U>(),
              (q) => q.None()
          )
  )
);
```

What I'm seeing is that if there are multiple edges from the 'Parent Vertex' to the 'Child Vertex' it will only ever return one of the children.  My goal is for the 'childVerts' KVP to have a value of some type of array with all vertices that the parent has an edge to. 

At the same time, I need a way to achieve functionality such that if the 'Parent Vertex' has NO out edges, I still somehow return some constant/value because I need to know the existence of the parent from the query.  Currently if the parent has no <Contains> edges, I receive this `Gremlin Query Execution Error: Project By: Next: The provided traverser of key \"childVerts\" maps to nothing` 

Any advice or suggestions would help, Thank You!

**Comment by danielcweber** [comment]
[Fold will probably help.](https://tinkerpop.apache.org/docs/current/reference/#fold-step).

**Comment by mike-kolback** [comment]
It almost as if somehow i forgot it existed. thank you.
