### ISSUE TITLE
partition key

### ISSUE THREAD

**Issue by smolesen** [ExRam/ExRam.Gremlinq#34]
When setting up a graph db in Cosmos you have to specify a partition key, and according to this post:

[Using a partitioned graph in Azure Cosmos DB](https://docs.microsoft.com/en-us/azure/cosmos-db/graph-partitioning)

you should then specify the partition key in all your queries, by adding:
````
.has('partitionKey', 'partitionKey_value')
````
Is there a way in Gremlinq to setup a partition key, or is it up to myself, to addd .has('partitionKey', 'partitionKey_value') to my queries?

TIA
Søren

**Comment by danielcweber** [comment]
Sorry, no support for that yet.

**Comment by smolesen** [comment]
Ok

**Comment by danielcweber** [comment]
It might be doable though since ids may be arbitrary objects. It is unknown to me yet what is the right wire-format for these complex (id, partitionKey) structures.

**Comment by smolesen** [comment]
In this post, 
https://medium.com/@jayanta.mondal/getting-the-best-out-of-cosmos-dbs-scale-out-graph-api-aka-partitioned-graph-containers-bf47c240e698

they give the following example:

g.withStrategies(PartitionStrategy.build().partitionKey('pk').readPartitions('pkX').create()).V('V1')

could that be a way to go....

**Comment by smolesen** [comment]
It actually seems like doint the followin works:
`
var g = GremlinQuerySource.Create("g.withStrategies(PartitionStrategy.build().partitionKey('pk').readPartitions('pkX').create())")
                        .UseLogger(logger)
                        .UseModel(graphModel)
                        .UseCosmosDb(settings.HostnameGraphDb, settings.Database, settings.Collection, settings.AuthKey);
`

**Comment by mike-kolback** [comment]
Hey @smolesen, do you know of a way to configure the partition strategy within the IGremlinQuerySource?

**Comment by matteobortolazzo** [comment]
No sure if there's any documentation about it, but for people having the same question, `g.V<TVertex>(id, partitionKey);` seems to work just fine

**Comment by utillity** [comment]
> No sure if there's any documentation about it, but for people having the same question, `g.V<TVertex>(id, partitionKey);` seems to work just fine

no, this actually does not work - each string in the list is considered an ID. So while this finds the record with the specified first parameter, it will NOT check, if the partitionKey matches! It just (probobly) wont find a record with such an ID.

**Comment by danielcweber** [comment]
This will work when instances of the CosmosDbKey-struct are passed into V(...).

**Comment by anheri** [comment]
so how do you get all vertices on a partitionKey?
I would expect to do something like this g.V<Vertex>(new CosmosDbKey("US"))
(US = if your partition your data on country codes)

But the CosmosDbKey only supports id,partitionKeyValue, which will always return 1 element
