### ISSUE TITLE
Nuget Release for NetCore 3

### ISSUE THREAD

**Issue by SebastianAtWork** [ExRam/ExRam.Gremlinq#35]
Hi, really cool and usefull library.
Can you make a release for .NetCore 3? Im getting Missing Method Exceptions with v 7.0.0-preview-0204. If i can help somehow, just let me know.

Greetings,
Sebastian

**Comment by danielcweber** [comment]
There'll be a stable release in a couple of days.

**Comment by danielcweber** [comment]
Before a stable release, I pushed another preview to NuGet: 7.0.0-preview-0220. Please have a try and let me know how it works for you.

**Comment by SebastianAtWork** [comment]
Sorry. I couldnt test it yet but i will let you know when i do. I had to  use the Gremlin.Net way for now since i cant wait at work and you never know how fast someone is with replying. But I will try it the next few days. Huge thanks :)

**Comment by danielcweber** [comment]
Fixed by recent stable release.
