### ISSUE TITLE
Preview the Gremlin Query before sending to Server

### ISSUE THREAD

**Issue by rauschy33** [ExRam/ExRam.Gremlinq#36]
Hello,

Sorry for the super basic question, but is there a way to view the gremlin query before sending it to the server?  This is very powerful library and am still working my way around it.

Thank you for any help.

**Comment by javaadpatel** [comment]
@rauschy33 I think you can call `.Profile()` on the query and then it shows all the steps that will be executed.

**Comment by rauschy33** [comment]
Thank you @javaadpatel.  Do you know if that will give me the Gremlin query that is being sent to the server?  I will try that again tonight; I believe I did previously but didn't get the actual string.  Maybe that is not how the library works but I was hoping I could use it to debug queries while creating the right graph schema.

Thank you again.

**Comment by javaadpatel** [comment]
@rauschy33 unfortunately it wont give you the actual query, you will have to interpolate the actual query from the steps. You can execute the string query and then compare it to the results you are getting from the library and then you will know if you have interpolated the query correctly.

**Comment by rauschy33** [comment]
Thank you @javaadpatel.  I assume this is because the library creates Gremlin Bytecode to send to the Gremlin Server?  My last question will be what happens when using CosmosDB since it doesn't support Gremlin Bytecode?  Is a query string created and send to the Cosmos Server?  Will this then change once CosmosDB does support Bytecode?

I am working my way through the library trying to debug, but it is taking me a little time to get through it.

I will close this after this.

Thank you again for your help.

**Comment by javaadpatel** [comment]
@rauschy33 from what i understand that is correct, it does not support byte code yet. @danielcweber would be able to give better insights but I think yes it is creating a query string and sending that to CosmosDB graph. 

I can't speak to what if anything will change once support for bytecode is added, that's up to @danielcweber to decide. 

Goodluck going through the code 👍

**Comment by danielcweber** [comment]
If you just wanna see what'll go to the server (albeit without sending it), you can setup the execution pipeline like [this](https://github.com/ExRam/ExRam.Gremlinq/blob/master/ExRam.Gremlinq.Core.Tests/ExecutionPipelinesTest.cs#L14) and echo the gremlin string.

Apart from this method, I would suggest setting up a logger. Gremlin will log all queries, however, without the parameters.

If you need some other means to hook into the execution, you can configure the execution pipeline and manually decorate the executor. The afforementioned link will give you some insight into how to do it.

**Comment by mouaxiong** [comment]
I'm following the suggestion provided from Daniel to add a logger.  Please see my attached image below.  When I explicitly log calling .Information, it works, but when I set it to the method UseLogger, nothing is being logged.  Am I missing something here?  Thanks.

![image](https://user-images.githubusercontent.com/1830670/73282404-34455100-41b7-11ea-8dc7-5973f3b8475a.png)

**Comment by danielcweber** [comment]
Make sure you got the lowest log level (Debug). Bytecode queries currently won't be logged.

**Comment by mouaxiong** [comment]
I guess I'm unclear from your comment above from Nov 4 regarding logging of queries.  You indicated that if you set up a logger, it should log all the queries.  Is that different from this logger?  I just want to make sure I understand the comment.  I see that when it hits an error, it logs errors but it's just not logging anything else.

**Comment by danielcweber** [comment]
You need to configure an execution pipeline (e.g. UseCosmosDB) after you setup the logger. Should be fine then.

**Comment by danielcweber** [comment]
From the latest preview on (> 8.0.0-preview-0196), check out the [latest update of the samples](https://github.com/ExRam/ExRam.Gremlinq.Samples/blob/master/ExRam.Gremlinq.Samples/Program.cs#L46). Query/Parameter logging has been reworked and made more configurable.

**Comment by utillity** [comment]
hi @danielcweber your link above does not work. I am also struggling with getting logging to work with my global AddLogger() configuration and also to get gremlinq to honor global logging configuration (ie. my ILoggingBuilder I use for the whole application). Not sure why gremlinq needs it's own ILoggingBuilder in .UseLogging()
