### ISSUE TITLE
Newtonsoft.Json

### ISSUE THREAD

**Issue by jurkrit** [ExRam/ExRam.Gremlinq#38]
Hi,

Is it possible to downgrade the Newtonsoft.Json package to version 11.0.2?
When using the package in Azure Function Apps, it has a hard dependency on Newtonsoft.Json 11.0.2 so the 2 version has a conflict?

**Comment by danielcweber** [comment]
Take a hard dependency on a higher version of Newtonsoft.Json in your Function App, should resolve the conflict.

**Comment by jurkrit** [comment]
This is not possible as the Microsoft nuget package with the function runtime has the hard dependency.

**Comment by danielcweber** [comment]
Still, you can take a dependency on whatever you want in your App. I have done it in a function app. There'll be a "detected package version outside of dependency constraint" warning, but it should work.

**Comment by danielcweber** [comment]
BTW, Microsoft.NET.Sdk.Functions 3.0.0-preview1 got a ">=" dependency on Newtonsoft.Json.

**Comment by jurkrit** [comment]
Agreed, maybe I am just full of nonsens cause I hate those warnings.

Trying to get rid of them.
So I guess you use something specific in Newtonsoft.Json 12.0.1

**Comment by jurkrit** [comment]
Yes I know, problem is the preview, cant use preview packages in this project

**Comment by danielcweber** [comment]
Company policy ?

**Comment by jurkrit** [comment]
Correct!

**Comment by danielcweber** [comment]
Closing since workaround exists.
