### ISSUE TITLE
Clone Vertex / Replace Implementation Change

### ISSUE THREAD

**Issue by whung1** [ExRam/ExRam.Gremlinq#39]
Because of CosmosDb constraints, I notice that the Update will always fail with partitionKey since it is specific to CosmosDb and the partition key is defined by the user. This can be avoided with some sort of knowledge passed to ExRam so it can be ignored on updates, but this functionality already exists (though not documented) so it is fine as is. 

The issue is when trying to update the vertex ID or the partition key, both these attributes are read only. Thus, the only way to "update" these is to recreate the vertex, which replace seems to imply doing. However, I noticed that replace in fact is just a helper function for vertex (unless I mis-read the code at this point in time) and thus would not work. 

During this "new" replace, some necessities would include remap any out-edges or in-edges associated with the old vertex when it is recreated with a different id/partition key, aka cloning.

Here's an example answer on a "clone" query for reference, but this does not work with Cosmos as they are behind on the Gremlin version the last time I tried directly: https://stackoverflow.com/questions/51900116/gremlin-clone-a-node-and-its-edges

**Comment by danielcweber** [comment]
>The issue is when trying to update the vertex ID or the partition key

I don't think there's a graph database that would actually support this.

**Comment by whung1** [comment]
Perhaps I am wrong on the best practices of a graph model design. 

Judging from how queries are made based on id and to leverage id uniqueness, it made more sense to approach the graph from a query perspective (in lines with Cassandra Data Modeling https://www.datastax.com/blog/2015/02/basic-rules-cassandra-data-modeling).

It also made sense from a graph perspective that nodes ids are based on specific properties (i.e. a person's name for a Person vertex/node). However, if a person's name changes or makes a typo, a id change is necessary. The alternative is to always query all your nodes of Person to find the one with name "x", but that seems possibly inefficient compared to ids, which presumably are indexed better.

So when I mean updating a vertexid/partitionkey, I meant from a business/user perspective, not a database perspective. The solution I proposed is obviously a workaround. 

I think Tinkerpop supports id change but it's a more of a helper DB than actual. Seems strange that the first graph you can try things with support id change but from a graph perspective we should not change ids.

**Comment by danielcweber** [comment]
I'm pretty sure, never change ids. If you find lookups on other properties to be slower, check indexes. I have stopped using DataStax though, so I can't help here.
