### ISSUE TITLE
Not Supported Exception: String Equals with StringComparison in Where

### ISSUE THREAD

**Issue by whung1** [ExRam/ExRam.Gremlinq#41]
Trying to do a V<SomeClass>().Where(x => x.Equals(someOtherValue, StringComparison.OrdinalIgnoreCase), but getting an Expression is not supported

Tried both ways for Equals with string in order to Ignore Case
```
ExRam.Gremlinq.Core.ExpressionNotSupportedException: An expression is not supported.\n ---> ExRam.Gremlinq.Core.ExpressionNotSupportedException: The expression 'x.Name.Equals(value(SomeClass+<>c__DisplayClass2_0).name, OrdinalIgnoreCase)' is not supported.

ExRam.Gremlinq.Core.ExpressionNotSupportedException: An expression is not supported.\n ---> ExRam.Gremlinq.Core.ExpressionNotSupportedException: The expression 'value(SomeClass+<>c__DisplayClass2_0).name.Equals(x.Name, OrdinalIgnoreCase)'
```

Is this possible to be supported or will a workaround be needed on my side?

Thanks for the hard work.

**Comment by danielcweber** [comment]
Won't work since there is no according Gremlin syntax for case-insensitive string-comparisons.
