### ISSUE TITLE
For the CosmosDb provider, is there a way to include system properties in a traversal?

### ISSUE THREAD

**Issue by brhinescot** [ExRam/ExRam.Gremlinq#414]
Such as "_etag". 

In a console I can start a traversal with g.withStrategies(ProjectionStrategy.build().IncludeSystemProperties('_etag').create()).V() to include the _etag property. Is there some way to configure the CosmosDb provider to include it?

**Comment by danielcweber** [comment]
There's unfortunately currently no way to specify strategies in ExRam.Gremlinq. Might be considered for the future though.

**Comment by TarekKassem** [comment]
Hi, any plans any soon for configuring the CosmosDb provider to include the strategies ?

**Comment by danielcweber** [comment]
@brhinescot, @TarekKassem, @utillity Please have a look at https://docs.gremlinq.net/extensions/, specifically at the Gremlin.Extensions.Strategies package.
