### ISSUE TITLE
No Way to Make Labels Variable

### ISSUE THREAD

**Issue by jonlave** [ExRam/ExRam.Gremlinq#43]
In ExRam, every scenario that involves getting a vertex or an edge, you have to provide an actually type of the vertex or edge you want, eg ( .V< User >(), or .InE< Knows >())), but what if I want to make this variable? There's no way to say .V(vertexLabel)() or .InE(edgeLabel) where vertexLabel and edgeLabels are strings or even types.

**Comment by danielcweber** [comment]
That's the whole point of Gremlinq: Abstracting away from label names to domain-types.

**Comment by danielcweber** [comment]
You can still have a property "Label" on a POCO base type and do something like

````
g.V<MyBaseType>().Where(x => x.Label == "label").
````

**Comment by danielcweber** [comment]
Passing Type-variables is definitely an idea worth considering, though it kind of defeats the purpose of an object-graph-mapper in my view.

**Comment by jonlave** [comment]
The scenario I have is, I can have multiple different types of edges between the same 2 nodes. Each edge implies different logic that can be done in the app. In my app, I need to do a lookup to determine if a subset of these edges exists between the 2 nodes and I only know this at runtime.

There is a workaround, but it's ugly. I would need to do some type of switch-case statement on the string label and for each case, return the exact .InE<Label> splice of the query. This is not ideal.

**Comment by jonlave** [comment]
Using the example you gave above with a base class, I'm trying to implement the best answer here: https://stackoverflow.com/questions/52447308/add-edge-if-not-exist-using-gremlin

which is to create an edge if it does not exists, but am facing issues with ExRam saying some of the operators don't exists, even though they do.

Gremlin query:

gremlin> g.V().has('person','name','vadas').as('v').
                  V().has('software','name','ripple').
                  coalesce(__.inE('created').where(outV().as('v')),
                                  addE('created').from('v'))

I didn't see any examples of using coalesce operator, which is typically used for an upsert pattern.

**Comment by danielcweber** [comment]
Well.....what does it say?

**Comment by jonlave** [comment]
Can you please post examples of how to:

- Find a specific edge between vertices. 
- Create an edge between two vertices if the edge does not already exists.

In both cases, you only have the edge label as a string and a base class for the edge. Also, you don't have the vertice id's, just a property value like 'Name'.

Also, I was unable to find .Filter() in ExRam which is another operator that would be useful in finding a specific edge. Is this by design or is present using another name?

**Comment by jonlave** [comment]
I finally got a working query for finding an edge between two specific vertices.
Vertices: User, Resource
Edge: RoleBase (base class), RoleX, RoleY, etc.

Graph model: User -> Role -> Resource

There are many types of roles a user can have, which determine access levels to a given resource.

public async Task<Bool> EdgeExists(string userName, string resourceName, string role) {
    var edge = await graph
        .V<User>()
        .Where(u => u.Name == name)
        .OutE<RoleBase>()
        .Where(e => e.Label == role)
        .As((__, e1) => __
            .InV<Resource>()
            .Where(r => r.Name == resourceName)
            .Select(e1))
        .FirstOrDefaultAsync();
    
    return edge != null;
}

**Comment by danielcweber** [comment]
Gremlinq supports the Coalesce step. What won't work if you use it?

**Comment by BenjaBobs** [comment]
> Passing Type-variables is definitely an idea worth considering, though it kind of defeats the purpose of an object-graph-mapper in my view.

To that effect, it would also be very handy to be able to be able to pass `PropertyInfo` variables.
Both would be very helpful in dynamic scenarios where you're not sure on compile time which types and properties you want to use for whatever you're doing.
An example of this is partial updates. If you're partially updating a vertex, you might want to pass a list of properties and their changes.

This (and other similar problems) can be solved currently by saving a selector expression for each property, and then passing those, but it's not really a pretty solution.

**Comment by BenjaBobs** [comment]
And loose all the niceness of this library? No way, I'd much rather use this. 😄

**Comment by danielcweber** [comment]
Closing due to the requested feature being out of scope for Gremlinq at this time. For filtering on labels, there is a workaround which has been presented. If Coalesce is buggy, please open a separate issue.
