### ISSUE TITLE
Please add support for /PartitionKey in the CosmosDb provider generated queries, it affects performance greatly

### ISSUE THREAD

**Issue by edwinvm** [ExRam/ExRam.Gremlinq#438]
Hi,

I'm struggling with getting .has("/PartitionKey", "value") in the generated query. Alternatively .has('/PartitionKey',within('value1','value2').

The problem is, that the only way to have the best performance in Cosmos Db Gremlin is to apply the Partition Key value to the query (when you know the PK). It looks like .has("PartitionKey", "value") works (without the / in front) but actually it doesn't work and only with the / it will be recognized as the true Partition Key value. 

To replicate this and see the result, you can basically make any query with .executionProfile() and try it with and without the / in front of PartitionKey (whetever the name you have choosen for it to be, it could the "PartitionKey" or "address", and see the execution time with and without the / before it.

Is there a possibility of manipulating the generated query, to for example do a .Replace("PartitionKey", "/PartitionKey") or use a 'magic string' in the query like for example:

var query = Gremlin.V<SomeVertex>().Where(x => "/PartitionKey" == "value");
or
var query = Gremlin.V<SomeVertex>().Where(a => partitionKeyList.Contains(a.PartitionKey)); <-- but then not a.PartitionKey but als result "/PartitionKey".

Or alternatively a build-in method like Gremlin.V<SomeVertex>().hasPartitionKey('value') or something like that.

If you have any suggestion how I can accomplish this it would be great, because the performance benefit in our case in the tests I've done with our current data set is over 600% faster execution time and over 600% less resources so it save a lot of time and money as well

**Comment by danielcweber** [comment]
Make PartitionKey a member on your entity POCOs and treat it like an ordinary property. If a partitionKey has to go inside the V as part of the key, use the 'CosmosDbKey' struct instead of raw string ids.

**Comment by edwinvm** [comment]
Thanks for your quick response! I will try the CosmosDbKey, we already had the PartitionKey as an ordinary property in our entity POCO's
