### ISSUE TITLE
Getting Vertex by Type

### ISSUE THREAD

**Issue by ambsoerensen** [ExRam/ExRam.Gremlinq#44]
Hi, I am just trying out Exram.Gremlinq for size, And i am struggling a with some pretty basic stuff. 
been through the samples numerous times now but i just can't figure out what i am doing wrong. 

Using cosmos db and are trying to create a simple CRUD endpoint for some accounts. 
I got the connection running and is fully able to create new vertexes. They appear as expected quering them using the data explorer in azure. 

But i cannot retrieve them again.

I try to get all accounts using below query. But it returns an empty list.
``` csharp
var accounts = _g.V<Account>();
return await accounts.ToListAsync();
```
Steps from above query. 
![image](https://user-images.githubusercontent.com/12606391/72267752-e52ce700-3620-11ea-8a73-d7f7f82ecccd.png)

I have a similar issue when retrieving vertexes by id. The collection returned is empty.
``` csharp
var accountQuery = _g.V<Account.Account>().Where(v => v.Id == id.ToString());
var account = await accountQuery.FirstOrDefaultAsync();
```

Steps from above query
![image](https://user-images.githubusercontent.com/12606391/72268961-127a9480-3623-11ea-84d4-fcedd1c1e2a5.png)

I Setup my connection like this. 
``` csharp
// setup connection
this._g = g.UseModel(GraphModel.FromBaseTypes<Vertex, Edge>()).UseCosmosDb(hostname, database, collection, authKey);
```
--

It is not clear to me how i can further debug query generated.

Any help or pointers would be greatly appreciated.

**Comment by danielcweber** [comment]
Could you post some json from one of your CosmosDB Data Explorer queries, stripped of any sensitive data? I assume that the label of the vertices you're trying to receive is not "Account".

**Comment by danielcweber** [comment]
Could you post a minimal working example project structure?

**Comment by ambsoerensen** [comment]
I have attached the project.

You need to add a cosmosdb to the AccountController in the AccountManagement project and  restore packages for the solution.
Everything else should be good to go. 
[exram.zip](https://github.com/ExRam/ExRam.Gremlinq/files/4058531/exram.zip)

in regard to the object stored in cosmosDb the label is actually "Account". 
output from data explorer:

Query: **g.V('28dafd80-91ca-4a39-b6eb-3748027218aa')** 
```json
[
  {
    "id": "28dafd80-91ca-4a39-b6eb-3748027218aa",
    "label": "Account",
    "type": "vertex",
    "properties": {
      "created": [
        {
          "id": "63a7c235-0b0b-46dc-84d6-13da2bd6aab7",
          "value": "2020-01-10T13:33:05.2574971Z"
        }
      ],
      "key": [
        {
          "id": "28dafd80-91ca-4a39-b6eb-3748027218aa|key",
          "value": "get test"
        }
      ],
      "name": [
        {
          "id": "51ffb048-e18f-47a9-91bf-105777704c64",
          "value": "get test"
        }
      ],
      "updated": [
        {
          "id": "e3fd039f-4847-4a23-9f43-3de14b4c6dbe",
          "value": "2020-01-10T13:33:05.2574971Z"
        }
      ]
    }
  }
]
```

**Comment by danielcweber** [comment]
How is Gremlinq supposed to know about the Account class? You're setting a model from base types Vertex and Edge, yet it seems that Account doesn't happen to be in that inheritance hierarchy. Try setting up a sensible model for the entities you're using.

I agree that Gremlinq shouldn't mute the traversal upon not recognizing the Account class and instead do some other best-effort-approach, but still, without setting a useful model, you won't get any inheritance support e.g.

**Comment by ambsoerensen** [comment]
The Inheritance hierarchy should be in place, but it is going through the "core" project. 
IVertex -> Vertex -> Metadata -> Account
[------------core----------------] [-Account Management-]

But that might be an issue?

**Comment by ambsoerensen** [comment]
In regard to behavior when unable to resolve the model hierachy a warning or an exception for that matter would suffice, rather then silently failing .

**Comment by danielcweber** [comment]
>The Inheritance hierarchy should be in place

Sorry, didn't spot that.

>But that might be an issue?

Yes., You need to pass additional assemblies to FromBaseTypes, specifically those you need Gremlinq to find inherited types in, in your case something like `typeof(Account).Assembly`.

**Comment by ambsoerensen** [comment]
i'll do that thanks 👍

**Comment by ambsoerensen** [comment]
Works like a charm. Thanks!
