### ISSUE TITLE
Drop() serializing into project step, causing GraphCompileException

### ISSUE THREAD

**Issue by BenjaBobs** [ExRam/ExRam.Gremlinq#45]
The following code `await _g.V().Drop().ToArrayAsync();` throws a `GraphCompileException` for me.

Env:
CosmosDB Emulator (v2.7.2.0).
ExRam.Gremlinq.Providers.CosmosDb 8.0.0-preview-0109

The error message is
`Gremlin Query Compilation Error: Column reference R_0["id"] cannot be located in the raw records in the current execution pipeline.`
From a console logger, Gremlinq printet the following:
`Error executing Gremlin query V().drop().project('id', 'label', 'type', 'properties').by(id).by(label).by(__.constant('vertex')).by(__.properties().group().by(__.label()).by(__.project('id', 'label', 'value', 'properties').by(id).by(__.label()).by(__.value()).by(__.valueMap()).fold())):`

I noticed that after the `drop()` step, a `project()` step is generated.
I think this goes against the intentions of the gremlin spec, since `drop()` always returns an empty set ([drop step](http://tinkerpop.apache.org/docs/current/reference/#drop-step)) so there would be nothing to project.

I *think* this is the cause of the `Column reference R_0["id"] cannot be located` error, as `id` is the first column in the `project()` step and it is unable to find data to fit into that column.

**Comment by BenjaBobs** [comment]
After looking through the commit history, I think my solution for now is to revert to v7 instead of v8 preview.

I think the commit [Introduce a notion of query semantics to properly suffix queries the correct bloat to get label, id, properties etc.](https://github.com/ExRam/ExRam.Gremlinq/commit/6fe73a5b08debe09da523c28b0e58fc01b2d6b70) introduces a nice idea of projecting the query results into a manageable data structure, but I'm not sure it fits all the applied cases.

**Comment by danielcweber** [comment]
Good spot.

**Comment by danielcweber** [comment]
Temporary workaround: Use `_g.V().Local(__ => __.Drop()).ToArrayAsync()` for the moment, even if it's maybe a bit slower.

**Comment by mouaxiong** [comment]
I am getting the same error as well.  Running on RC 8.0.0.  I tried the workaround suggested and that didn't fix it either.  Would you suggest going back to version 7?  Any help would be appreciated here.  Thank you.

**Comment by BenjaBobs** [comment]
I got it working by manually projecting a constant after the drop step. That way you get no extra projection.

**Comment by danielcweber** [comment]
A new preview will be released on NuGet today.

**Comment by danielcweber** [comment]
The latest preview version is now 8.0.0-preview-0127.

**Comment by mouaxiong** [comment]
Thank you.  I just updated to that and seems to have fixed it.
