### ISSUE TITLE
Where(x => x.Id.ToString() == "123")

### ISSUE THREAD

**Issue by jonathaneckman** [ExRam/ExRam.Gremlinq#452]
I'm trying to run this query in Gremlinq:

```
g.V('95f1c9c7-499e-469a-9c6c-16b9190614ff')
    .as('parent')
    .out('hasChild')
        .where(eq('parent'))
            .by(id)
            .by('childId')
```

This seems like the answer...

```
var result = await _graphContext
      .V<Parent>(parentId)
      .As((__, thisParent) => __
          .Out<HasChild>()
          .OfType<Child>()
          .Where(child => child.Id.ToString() == thisParent.Value.ChildId)
      )
      .FirstOrDefaultAsync();
```

...but I get the following runtime error:

> 'The expression 'child => (child.Id.ToString() == value(MyProject.API.Repositories.ParentsRepository+<>c__DisplayClass2_1).thisParent.Value.ChildId)' is not supported.'

Is this possible with this library? Any suggestions on what I'm missing? I can make a repro project if necessary.

**Comment by danielcweber** [comment]
ToString won't ever work. If types don't match, try casting ((string)child.Id, or (string)(object)child.Id if child.Id is a value type.) This should work. If it doesn't, please send a minimal repro (or add a failing unit test in a PR).

**Comment by jonathaneckman** [comment]
🤦‍♂️ that was it. So simple. Thank you!
