### ISSUE TITLE
Error launching Gremlinq samples

### ISSUE THREAD

**Issue by ideagpsadmin** [ExRam/ExRam.Gremlinq#465]
I'm getting the following error on launching the Gremlinq samples project.  Please advise..

![gremlinq_samples_error](https://user-images.githubusercontent.com/15199520/132918108-4d7ff6ef-901c-40e8-96e6-2e1d04dadac0.png)

**Comment by danielcweber** [comment]
Exception says "(...) or set AllowSynchronousIO to true", which is the case in the [latest sample code](https://github.com/ExRam/ExRam.Gremlinq.Samples/blob/76cd4cc382d8d65b98a790560f8ba89fd8a6824e/ExRam.Gremlinq.Samples.AspNet/Program.cs#L24). As a consequence, I can't reproduce the behaviour, it runs just fine for me. So I assume you changed the code or copy-pasted the seemingly relevant parts into your application but forgot to set the option. Check the 'AllowSynchronousIO' option. If it persists nonetheless, you'll need to provide some minimal working repro code.
