### ISSUE TITLE
Selecting a vertex returns null after successfully inserting the record using where parameter.

### ISSUE THREAD

**Issue by mouaxiong** [ExRam/ExRam.Gremlinq#48]
I don't know if I'm missing something here but I'm simply performing a select with a where on lastname as shown below in the screenshot.  In the addV method, I get a vertex back which is the object that was inserted, however in the next statement, I try to retrieve it and I'm getting a null.  Any  advice on what I may be doing wrong or am missing?  I have the User class appropriately decorated with the IVertex interface.  Thanks in advance.

![image](https://user-images.githubusercontent.com/1830670/73282768-bcc3f180-41b7-11ea-9719-e979a69df0c4.png)

**Comment by danielcweber** [comment]
It'll be really hard to comment on your code if I don't see the whole setup. Please post a minimal working repro.

**Comment by mouaxiong** [comment]
[Test_app.zip](https://github.com/ExRam/ExRam.Gremlinq/files/4123640/Test_app.zip)
I've zipped up a small test that simulates the two issues I'm running into.  The first one is the select where the value is null and then the other issue is with the logger.  When used with "UseLogging" in the configuration, it doesn't appear to be logging the queries as I had hoped.  Any guidance would be appreciated.  Thank you.

**Comment by danielcweber** [comment]
Use `_g` on your second query. You're using `g`, which is totally unconfigured.

I wonder whether it's a good idea to even allow queries on `g`, since 99% of the time, it won't do what the user expects.

**Comment by mouaxiong** [comment]
Wow.  I'm not sure how I missed that.  Thank you for catching that.  I've been so worried about the other pieces of code that I totally overlooked that.  I do like you suggestion about not letting g be used since it's not the configured instance.  Thanks so much on this one.

**Comment by mouaxiong** [comment]
This is more related to my other issue I submitted but since I have the example code here, I'm trying to get the logger to work and I already have the execution pipeline as you suggested.  However, it's still not working as expected.  Do you know if I'm missing something here?  I would love for the logger to work so I can see the queries being executed.  Thanks again.

https://github.com/ExRam/ExRam.Gremlinq/issues/36

**Comment by danielcweber** [comment]
The Trace level is even below debug, right? Try not filtering any logs at all. Use "UseCosmosDb" after "SetLogger".

**Comment by mouaxiong** [comment]
I already had the usecosmosdb there.  After you made the comment that the logger was using a trace level, I realized I needed to set the level to "verbose" in the case of serilog.  Thank you for your help Daniel.  It's been very helpful.  Setting it to "verbose" allowed for the queries to come through.
