### ISSUE TITLE
Unable to add edge to two existing vertex.

### ISSUE THREAD

**Issue by mouaxiong** [ExRam/ExRam.Gremlinq#49]
**Describe the bug**
I'm trying to add an edge between two existing vertices.  I'm getting the error message as below.  I'd like an example if possible of how to use the "AddE" method to add the edge to two existing vertexes if possible.  I can't seem to get an example to work in the test project.

ExceptionMessage :
	Value of variable _b is not a constant type. Cannot assign complex values to groovy variable.
	Parameter name: value
Source : Microsoft.Azure.Cosmos.Gremlin.Core
	HResult : 0x80070057

**Expected behavior**

Below is sample code:
I would expect that the edge gets added to both vertices.

// testClient is a result received in a previous statement using the _g.V()
var hasClient = await _g.AddV(test).AddE<HasClient>().To(__ => __.V(testClient));

**Version information**
using version 

**Minimal working example**

**Additional context**

**Comment by danielcweber** [comment]
V takes IDs. It's like in plain Gremlin. You have to pass a vertex ID to V.

**Comment by mouaxiong** [comment]
Thanks.  That helped me get to where I needed to go.
