### ISSUE TITLE
Question: Can we set camelCase serialization?

### ISSUE THREAD

**Issue by matteobortolazzo** [ExRam/ExRam.Gremlinq#499]
Hi,

I tried to find documentation, especially around configuration (`g.ConfigureEnvironment`).

My DB is using camel case properties, but with Gremlinq new objects are created with pascal case, ignoring both `JsonProperty `and `JsonPropertyName`.

Is there anything I can do about it?

Thanks a lot

PS: this library is far better than the alternatives! 🙂

**Comment by danielcweber** [comment]
You can find an example in a unit test [here](https://github.com/ExRam/ExRam.Gremlinq/blob/main/test/ExRam.Gremlinq.Core.Tests/GraphModelTest.cs#L217) on how to configure serialization of labels, also using camel case.

**Comment by matteobortolazzo** [comment]
Thanks!!
