### ISSUE TITLE
Updating Vertex and Edge objects

### ISSUE THREAD

**Issue by SyntaxUnknown** [ExRam/ExRam.Gremlinq#5]
First off, I love the library. We're just kicking off a Cosmos Graph project and it looks like this is going to be a great help!

We need to be able to perform CRUD operations on the Vertex and Edge objects. I was looking for something like AddV where I can just pass in the object and have all the properties saved. I didn't really want to have to manually issue Property calls for each possible change.

So, I took a stab at it and implemented "UpdateV" (I realize this isn't standard, but seemed like it would be nice). 

Here's a quick look at how a save operation would look:

```
public async Task<Person> SaveAsync(Person person)
{

    var personVertex = _mapper.Map<PersonVertex>(person);

    if (personVertex.Id == null)
    {
        personVertex.Id = Guid.NewGuid().ToString();
        personVertex = await _g.AddV(personVertex).First();
    }
    else
    {
        personVertex = await _g.V(personVertex.Id).UpdateV(personVertex).First();
     }

     return await GetPersonAsync(personVertex.Id.ToString());
}
```

Internally, we just drop all the properties and add the updated properties. Here's my implementation:

```
private GremlinQuery<TVertex, Unit, Unit, Unit, Unit, Unit> UpdateV<TVertex>(TVertex vertex)
{
    return this.AddElementPropertiesForUpdate<TVertex>(vertex);
}


private GremlinQuery<TNewElement, Unit, Unit, Unit, Unit, Unit> AddElementPropertiesForUpdate<TNewElement>(object element)
{
    var elementType = element.GetType();

    // Only pull back the properties without the ReadOnly attribute
    var props = element.Serialize().Where(p => !Attribute.IsDefined(p.Item1, typeof(ReadOnlyAttribute)));

    // Drop the properties we found from the existing item
    var drop = Anonymize().Properties<Unit, Unit, Unit>(props.Select(p => p.Item1.Name))
                       .Drop();

    var ret = AddStep<TNewElement, Unit, Unit, Unit, Unit, Unit>(new SideEffectStep(drop));

    // Re-add the properties
    foreach (var (propertyInfo, value) in props)
    {
        ret = ret.AddStep(new VertexPropertyStep(propertyInfo.PropertyType, Model.GetIdentifier(elementType, propertyInfo.Name), value));
    }

    return ret;
}
```

We obviously don't want to update every property, especially the Id and possibly the partition key, so I implemented an attribute-based solution for excluding properties from this update (this is the base class for my graph items):

```
    public abstract class Vertex : IVertex
    {
        [ReadOnly]
        public object Id { get; set; }

        [ReadOnly]
        public string Type => GetType().Name;

        [ReadOnly]
        public string PartitionKey => $"{Type}_{Id}";

        public bool IsDeleted { get; set; }

    }
```

It seems to work pretty well. Does something like this fit with your vision of the library? I'll be happy to issue a PR if you think it's a good idea. If not, let me know if there would be a better direction for something like this.

Thanks,
Andy

**Comment by danielcweber** [comment]
I will get back to this issue on monday.

**Comment by danielcweber** [comment]
I want to avoid attribute based configuration if at all possible. User might not have control or source access to the POCOs they use.

But I definitely recognize the need for a means to update.

**Comment by SyntaxUnknown** [comment]
I guess I didn't notice that it was possible to use POCOs in which the user didn't have control. That's pretty cool.

In that case, what do you think about being able to specify a property filter on the UpdateV and UpdateE calls like this:

```
g
  .V<Person>()
  .UpdateV(person, (property) => property == nameof(Person.Name) || property == nameof(Person.RegistrationDate))
  .Should()
  .SerializeToGroovy<TVisitor>("g.V().hasLabel(_a).sideEffect(__.properties(_b, _c).drop()).property(single, _b, _d).property(single, _c, _e)")
  .WithParameters("Person", "Age", "Gender", 21, Gender.Male);
```
The optional 2nd parameter would allow users to specify the properties to exclude from the update.

I'd still keep the `[ReadOnly]` attribute because I think it's easier to maintain and is pretty common for libraries like this, but the 2nd filter parameter would give you full control.

**Comment by danielcweber** [comment]
Part of the new Gremlinq 7.0.0 preview.
