### ISSUE TITLE
Question: [CosmosDb] Getting consumed RU/s 

### ISSUE THREAD

**Issue by Adelzu** [ExRam/ExRam.Gremlinq#50]
Hi,
Is there an easy way to get the consumed RU/s for the executed query, It seems that the easiest way to do that is to create a IGremlinQueryExecutor, which is kind of overkill. Or am i missing something here?

As we are using application insights, i want to append the total RU/s consumed during that request to the RequestTelemetry in order to have a better understanding where we need to optimize.

**Comment by danielcweber** [comment]
It's unfortunately not possible currently without overriding the executor and the whole execution pipeline.

**Comment by nilshedstrom** [comment]
I added a LogResults-method to WebSocketGremlinQueryExecutor
```
            private void LogResults(ResultSet<JToken> results)
            {
                if ((_logger?.IsEnabled(_loggingOptions.LogLevel)).GetValueOrDefault() && _loggingOptions.Verbosity > QueryLoggingVerbosity.None)
                {
                    _logger?.Log(
                        _loggingOptions.LogLevel,
                        "Executed query with total-request-charge {0} and total-server-time-ms {1}",
                        results.StatusAttributes["x-ms-total-request-charge"], 
                        results.StatusAttributes["x-ms-total-server-time-ms"]
                    );
                }
            }
```
And then I call that from the Execute method
```
public IAsyncEnumerable<object> Execute(object serializedQuery)
            {
                return AsyncEnumerable.Create(Core);

                async IAsyncEnumerator<object> Core(CancellationToken ct)
                {
                    var results = default(ResultSet<JToken>);

                    if (serializedQuery is GroovyScript groovyScript)
                    {
                        Log(groovyScript);

                        try
                        {
                            results = await _lazyGremlinClient
                                .Value
                                .SubmitAsync<JToken>($"{_alias}.{groovyScript.QueryString}", groovyScript.Bindings)
                                .ConfigureAwait(false);
                            LogResults(results);
                        }
```
It works for me but could probably use some error handling

**Comment by danielcweber** [comment]
Good thinking. Problem is that we now have the mention of Microsoft-specific headers in the basic WebSocket-executor. If you find a way to lift it up into the CosmosDB-executor and make it a PR, we might have a feature here.

**Comment by danielcweber** [comment]
This has finally been made possible through an extension library:

https://docs.gremlinq.net/extensions/diagnostics/
