### ISSUE TITLE
Question: how to create a "where without" clause?

### ISSUE THREAD

**Issue by drewyoungdev** [ExRam/ExRam.Gremlinq#51]
Hello!

First wanted to thank you on creating this library, it's been super helpful as I've been starting to explore graph databases.

I currently have the following relationships set up:

`User` - `Follows` -> `User`

I'm trying to create a Recommendations query to grab a list of recommended `Users` that `Follows` `Users` that the `Current User` directly `Follows`. So essentially `User` vertices that are two-hops away on the `Follows` edge.

However, I want to **_exclude_** the current `User` from that list as well as any `Users` that the `Current User` directly `Follows` (anything one-hop away on the `Follows` edge)

I found within the tinkerpop documentation for Recommendations how to achieve this and was able to get the desired result with the following query (http://tinkerpop.apache.org/docs/current/recipes/#recommendation):

`g.V().has('id', '{user_id}').as('self').out('Follows').aggregate('direct-follows').out('Follows').where(neq('self')).where(without('direct-follows'))`

Trying to use Gremlinq, I came up with the following: 

```  
await _g
    .V<User>(userId)
        .As((_, self) => _
            .Out<Follows>()
            .Aggregate((__, directFollows) => __
                .Out<Follows>()
                .OfType<User>()
                    .Where(x => x != self
                        && !directFollows.Contains(x)))) // How to exclude directFollows?
                .OfType<User>()
                .ToArrayAsync();
```
which works up until the `directFollows.Contains(x)` expression in which case it returns the ExpressionNotSupportedException.

I've been able to replicate it by combining the results of two separate queries but that seems inefficient: 

**[Example](https://github.com/drewyoungdev/App.UserGraph.Api/blob/1d4ecd8773c2efb22cd016497e7b9fe826c514c6/UserGraph.DataLayer/RecommendationsRepository.cs#L53)**

Is this the correct way to approach this or is there a better way? Or is this functionality just not yet supported?

Thanks :)

**Comment by danielcweber** [comment]
Would you be able to not aggregate into the directFollows list, but put every follower in scope (with 'as') and then filter on x != directFollower, just like you did with user?

In a nutshell: Try not aggregating, but have single users "self" and "follower" in scope, then filter them out. Would that work?

**Comment by drewyoungdev** [comment]
Thanks for the quick response!

So I tried that but it didn't seem to work as intended:

`g.V({user_id}).hasLabel('User').as('self').out('Follows').as('directFollower').out('Follows').hasLabel('User').where(neq('self').and(neq('directFollower')))`

I **_think_** the following is happening:

- `User1` - `Follows` -> `User2`
- `User1` - `Follows` -> `User3`
- When you start at the `User1` vertex, you traverse the `Follows` edge to `User2` and `User3`
- However, I think the `directFollower` that's stored and used for comparison is relative to the vertex that started the traversal. So when you fan out on `User2`, each comparison made in the `where` clause would only be against the start point for that traversal `User2`?
- Since each `User` cannot follow themselves, they are never excluded.

I did find an alternative where I aggregated both collections of `direct followers` and `two-hop followers` and have my application do the comparison/exclusion to get the distinct list.

**[Example](https://github.com/drewyoungdev/App.UserGraph.Api/blob/b2c4863edd340b10f90dab6d6b96c27fb2088ebc/UserGraph.DataLayer/RecommendationsRepository.cs#L54)**

So I guess before I close out the Issue, I just wanted to make sure that at the moment is there any way to generate the `.where(without('step-label'))`?

Thanks!

**Comment by danielcweber** [comment]
Well, it *should* work as intended....will investigate in a couple of days.

**Comment by danielcweber** [comment]
Make sure you update to 8.0.0-preview-0161 and try again. The update to 8.x is breaking but straightforward (check the samples again if necessary)

**Comment by drewyoungdev** [comment]
Worked as expected with the original query as expected! Thank you 👍
