### ISSUE TITLE
Question: Ignore property on update

### ISSUE THREAD

**Issue by kyiw** [ExRam/ExRam.Gremlinq#52]
Is it possible to ignore properties on update?

I found the IgnoreOnUpdate flag in your code but could not make it work. Currently my workaround is deleting the vertex and adding it again, but this feels kinda dirty and I would like to have it in a more clean way.

**Comment by danielcweber** [comment]
Have a look at [this unit test](https://github.com/ExRam/ExRam.Gremlinq/blob/4c8232e62a515fd1e6cb06901d93a6383626e4be/ExRam.Gremlinq.Core.Tests/GraphModelTest.cs#L280). It should give you some direction on how to achieve what you need.

**Comment by kyiw** [comment]
Thanks for the fast reply, it works!
Maybe it would be nice to be able to configure such things via attributes in the future?

Best regards,
kyiw

**Comment by danielcweber** [comment]
Gremlinq deliberately steps away from attributes because not everyone might have source access to the entities.

**Comment by utillity** [comment]
Hi Daniel, while I agree with your argument - the one thing does not exclude the other. Exram could support both attributes AND configuration based scenarios.
