### ISSUE TITLE
Serialize and Deserialize using camelCase instead of PascalCase

### ISSUE THREAD

**Issue by diego-samano** [ExRam/ExRam.Gremlinq#526]
**Is your feature request related to a problem? Please describe.**

Gremlin standard is camelCase. Using Gremlinq package serializes classes as they are, so if class name is Developer, then label will be "Developer". When limiting or scoping to Gremlinq + .Net solution this shouldn't be a problem, but when using other tools and platforms this may lead to inconsistent values. So anything comming from other places will likely use camelCase, and due to Gremlin is case sensitive having "Developer" or "developer" will not match as the same type. Same case is for properties. This is specially a problem when you depend on data feeds and import/export tools that uses camelCase (Gremlin conventions) instead of PascalCase (.Net conventions)

**Describe the solution you'd like**

Would be nice to have a configuration option to ensure serialization/deserialization is able to handle between camelCase and PascalCase (as typically is done by JSON libraries) so Gremlin records can be written using its own conventions and .Net solutions the appropiate as well.

**Describe alternatives you've considered**

My workaround was writing class and property names as camelCase instead. Unfortunately this causes code smells on our Quality Gates (this can be muted, so this could be ignored) and is prompt to errors by someone not aware of this, using .Net conventions.
Another option is to create our custom wrapper using a Query Builder pattern to send queries as http requests to our endpoint instead of using this library.

**Comment by ambsoerensen** [comment]
Hi trying to do the same for properties but have a solution for the labels, 

When setting up the querysource you can specify the casing style for the labels. 

``` Csharp
.ConfigureEnvironment(env => env.UseModel(GraphModel.FromBaseTypes<Vertex, Edge>(lookup => lookup.IncludeAssembliesOfBaseTypes())))
                .ConfigureEnvironment(env => env.ConfigureModel(modelTransformation => modelTransformation
                .ConfigureElements(transformation => transformation.UseCamelCaseLabels())))
```

**Comment by diego-samano** [comment]
Awesome! Thanks for your response. Just one question about line below. What is the purpose of that one?

`.ConfigureElement<Vertex>(conf => conf.IgnoreOnUpdate(v => v.Key)))`

**Comment by ambsoerensen** [comment]
That's my partition key, i'm using cosmos DB where the pkey cannot be changed.
