### ISSUE TITLE
Add g.With(..) To Allow Configuration On A Query Basis

### ISSUE THREAD

**Issue by martin-shields-sage** [ExRam/ExRam.Gremlinq#532]
**Is your feature request related to a problem? Please describe.**
Allow the use of g.with(...) so that options can be configured on a client basis. 

The reason to add this is that I require to set timeouts on a query level as shown in this link : https://docs.aws.amazon.com/neptune/latest/userguide/best-practices-gremlin-java-per-query-timeout.html

With Configuration
The with() configuration adds arbitrary data to a TraversalSource which can then be used by graph providers as configuration options for a traversal execution. This configuration is similar to with()-modulator which has similar functionality when applied to an individual step. - https://tinkerpop.apache.org/docs/current/reference/#configuration-steps-with

**Describe the solution you'd like**
Add in .With(..) that takes 2 parameters one being the configuration parameter and the other being the value.

**Describe alternatives you've considered**
I have not found any other alternatives, if there is one that you could point me to it would be greatly appreciated.

**Comment by danielcweber** [comment]
Noted. PRs are welcome though.
