### ISSUE TITLE
How to evaluate a property of an edge in Gremlinq?

### ISSUE THREAD

**Issue by robertmrobo** [ExRam/ExRam.Gremlinq#55]
I have this query which I am able to run on Gremlin Console successfully. 

```
g.V("a2cc3ae8-2a61-4107-876a-1e0506c25d5b")
.outE("CompHasSeason").has("IsCurrent", true)
.inV().has("CompetitionId", "a2cc3ae8-2a61-4107-876a-1e0506c25d5b")
.valueMap(true).unfold()
```

When ran, it successfully returns a `Season` vertex which is connected to a `Competition` vertex by an edge which has a property `IsCurrent` which indicates if the season is a current season (eg. 2019/2020).

Now on my Data Access Layer, I have a repository which I want to run the exact same query using Gremlinq. I tried the following code(s).

`                var season = await GremlinQs
                    .V<Competition>(competitionId)
                    .OutE<CompHasSeason>()
                    .InV<Season>().Where(s=>s.CompetitionId == competitionId)
                    .FirstOrDefaultAsync();`

`                var season = await GremlinQs
                    .V<Competition>(competitionId)
                    .OutE<CompHasSeason>().Where(x=>x.IsCurrent)
                    .InV<Season>().Where(s=>s.CompetitionId == competitionId)
                    .FirstOrDefaultAsync();`

The above code does gives me the season, but it doesn't evaluate the edge's property `IsCurrent`. When I execute the code below in a attempt to evaluate the `IsCurrent` property, I always get null.

Last but not least, I understand this is not the ideal place to bring such questions, please point me where I can post such questions and get almost immediate reply which i get whenever I post here. On SO questions like this are rarely answered. Already tried a couple of times.

**Comment by danielcweber** [comment]
Not sure what you mean by "evaluating the property of the edge"...if an edge is returned, its property will be set. Do you mean there's not even an edge returned? You sure it should be in the result set, given the filters you set up?

It's really hard to say anything here. That's why in the issue template, I ask for a minimal working example in the form of a unit test, or a repo.
