### ISSUE TITLE
How to clone a vertex with edges

### ISSUE THREAD

**Issue by danielcweber** [ExRam/ExRam.Gremlinq#553]
### Discussed in https://github.com/ExRam/ExRam.Gremlinq/discussions/552

<div type='discussions-op-text'>

<sup>Originally posted by **rautjris** February 25, 2022</sup>
Hi !

Need some advice how to clone a Vertex with it's properties and Edges/edge properties to a new Vertex.
I'm newbie with gremlin and using Cosmos Db gremlin.

This is what I have now:

await _g.V<SampleVertex>(sourceid).As((_, source) => _
 .AddV(new SampleVertex())
 .As(( _ , clone) => _
 .SideEffect(s =>
 {
 return s.Select(source).OutE<SampleEdge>().As(( _ , e) => _
 .Select(e).InV().AddE<SampleEdge>().From(f => f.Select(clone)));
 }
 )
));

But I'm out of ideas how to copy properties.

Thanks in advance
</div>

**Comment by danielcweber** [comment]
For clarification: It seems that you're trying to write a query in Gremlinq when it's unclear how the query could be written in raw Gremlin. Such questions are probably better formed as a question on [https://groups.google.com/g/gremlin-users](the mailing list).

**Comment by rautjris** [comment]
@danielcweber I'm using the ExRam.Gremling and trying to do similar "clone a node and it's edges" like in this Stackoverflow post using the ExRam.Gremling.
https://stackoverflow.com/questions/51900116/gremlin-clone-a-node-and-its-edges

So I'm selecting the source properties and trying to set those in clone properties.
.Select(clone).Property(p.Value.Key, p.Value.Value)); sounds promising but looks like it is not the way to go.

            var result =  _g.V<SampleVertex>(sourceid).As((_, source) => _
                .AddV<SampleVertex>()
                .As((_, clone) => _
                .SideEffect(s =>
                {
                   return s.Select(source).Properties().As((_, p) => _
                    .Select(clone).Property(???));
                    //what to put here? raw gremlin should be like: property(select('p').key(), select('p').value())).
                }
                )
                .SideEffect(s =>
                        {
                            return s.Select(source).OutE<SampleEdge>().As((_, e) => _
                            .Select(e).InV().AddE<SampleEdge>().From(t => t.Select(clone)));
                        }
                    )
                )).Debug();

**Comment by danielcweber** [comment]
>> what to put here? raw gremlin should be like: property(select('p').key(), select('p').value())).

That would surely work well in Gremlin, however, property-overloads that would take traversals for key and value are, as it is now, not part of Gremlinq. It might be implemented in an upcoming release though. PRs, as always, are always appreciated.
