### ISSUE TITLE
Property Casing With Cosmos Gremlin

### ISSUE THREAD

**Issue by dakota-graffle** [ExRam/ExRam.Gremlinq#555]
I had noticed that the Gremlin .NET SDK saves the class properties as pascal and used your setting to set them all to camelCase in the Cosmos Gremlin DB. The problem I'm finding is that when using LINQ to create point reads on my Partition Key the LINQ does not match with the camelCase that is being written to the graph but instead is comparing the Pascal casing. Is there a setting I'm missing to have the casing respected on the query the same way it is respected when being written?

**Comment by danielcweber** [comment]
#499, #526 and #534 seemed to help people the most.
