### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by jurkrit** [ExRam/ExRam.Gremlinq#60]
Hi,

I am trying to use the .where(string lambda), but I an not sure how to use it.
What is the syntax of the lamda if I want to query on a property?

**Comment by danielcweber** [comment]
https://github.com/ExRam/ExRam.Gremlinq/blob/0694374611f8d75e1b14ada9ef366922c66fe8a1/ExRam.Gremlinq.Core.Tests/GroovySerializationTest.cs#L977

**Comment by danielcweber** [comment]
Assuming you are using a 8.x preview. 7.x has the raw strings but really it's deprecated.

**Comment by jurkrit** [comment]
Cool thanks, no I am still on 7.0.6. Waiting for 8 to come out of preview.
