### ISSUE TITLE
Cannot add a vertex where the partition key property has value 'null'.

### ISSUE THREAD

**Issue by DocGreenRob** [ExRam/ExRam.Gremlinq#602]
**Describe the bug**
Unable to run the sample app after cloning. I get an error that says something about a partition.

**Expected behavior**
I expected the sample application to work properly.

**Version information**
(whatever is in the sample application as of today)

**Additional context**
I created a new Graph DB, and a Graph. I named the partition key "pk". I then updated the value of the PartitionKey property of the Vertex class, and still no luck. I created another Graph db w/o a partition key and still this gave the same error.

**Comment by danielcweber** [comment]
https://github.com/ExRam/ExRam.Gremlinq/issues/463#issuecomment-900522353

**Comment by DocGreenRob** [comment]
Thanks, that was it!
