### ISSUE TITLE
HowTo: g.V().has('xyz') for various labels?

### ISSUE THREAD

**Issue by ruthoferroman** [ExRam/ExRam.Gremlinq#603]
Hi!
This might be a beginner questions, but I would really appreciate any help. I'm trying to get all items that have a specific property - no matter which label they have (from my CosmosDb). 
The query I would like to have is something like `g.V().has('xyz')`
Is there a way to do this with ExRam.Gremlinq?

**Comment by danielcweber** [comment]
How about 

```
g
    .V()
    .Where(t => t.Property != null)
````

**Comment by ruthoferroman** [comment]
@danielcweber  thanks for your suggestion!

basically the Where() works as long as i pass the correct object type like:
```
g
    .V<Person>()
    .Where(x => x.Name != null)
```
but your example wouldn't work since the lamba in .Where(...) need a type, right?

I have literally hundreds of different object types and giving a abstract class to be able to write the lambda expression doesn't return a result.
```
g
    .V<AbstractClassOrInterface>()
    .Where(x => x.Name != null)
```

**Comment by danielcweber** [comment]
Have you tried g

```
g
    .V()
    .Where(x => x.Property != null)
```

**Comment by danielcweber** [comment]
The usage of a base vertex type is strongly recommended. In fact, you will get into trouble with inheritance when the model doesn't work on a common vertex/edge base type.

**Comment by danielcweber** [comment]
You could do without the base element classes with something like

```
g
    .V()
    .Where(__ => __.Properties("xyz"))
````

but don't. Use base classes.

**Comment by ruthoferroman** [comment]
i found the problem why i didn't get items when i used the base type in my query:

the baseclass was in a different assembly than the inherited classes - so i had to load that assembly 
```
.FromBaseTypes<AutomationAppBase, Edge>(lookup => lookup
                .IncludeAssembliesOfBaseTypes()
                .IncludeAssemblies(new List<Assembly> { AssemblyHere }))
```

thanks for your help!!!
