### ISSUE TITLE
Can't Build Solution

### ISSUE THREAD

**Issue by DocGreenRob** [ExRam/ExRam.Gremlinq#608]
**Describe the bug**
I cloned your repo and can't build it. I get build errors:

![image](https://user-images.githubusercontent.com/7489324/161299026-6441232a-5a65-4d3c-a622-7e488998097a.png)

**Expected behavior**
It should build properly

**Version information**
I just cloned the repo 3/31/2022

**Comment by danielcweber** [comment]
Cannot reproduce either locally (VS 2022) or on [the latest run on the build server](https://github.com/ExRam/ExRam.Gremlinq/actions/runs/2058310584).

**Comment by DocGreenRob** [comment]
Thanks! (I tried w/VS 2019)
