### ISSUE TITLE
OfType<T>() is broken

### ISSUE THREAD

**Issue by DocGreenRob** [ExRam/ExRam.Gremlinq#609]
**Describe the bug**
I am trying to implment a wrapper around your client and am running into issues w/the OfType<T>() method. I'm trying to replicate the `How_many_pets_does_everybody_have()` method from the test project. I am getting a different result than you are. I am pointing to the same Database and Graph and have the same object model in both projects. 

The `OfType<T>()` when `T` is a base class (i.e., `Pet`) is expected to reflect and determine any classes that inherit from it and should return a list of `Type`s (i.e., `Dog, Cat, Pet`).

Your test project produces:
`V().hasLabel('Person').out('Owns').hasLabel('Cat','Dog','Pet')` which is correct and what I expect.

My implementation produces:
`V().hasLabel('Person').out('Owns').hasLabel('Pet')` which is incorrect.

I have the same exact code, same class model, but different output. I tried cloning your repo and fixing whatever the issue is in the `OfType<T>()` extension but the solution won't build.

Here is my code and some screenshots showing what's going on:

1. My code is on left
2. Your sample project is on the right
3. You will see that I don't get **Cat** or **Dog**

![image](https://user-images.githubusercontent.com/7489324/161302552-09f38fa4-5a46-4d07-9a13-1d94280e42c9.png)

**Pet**
![image](https://user-images.githubusercontent.com/7489324/161302820-571aab13-f931-40f1-86bc-dc2c82303a0b.png)

**Mammal**
![image](https://user-images.githubusercontent.com/7489324/161302903-c3c1f2b1-ae4e-4ab1-98fd-611817b9c253.png)

**Vertex**
![image](https://user-images.githubusercontent.com/7489324/161303006-f9869bb5-664d-4925-9b36-ca541b49e98c.png)

**Dog**
![image](https://user-images.githubusercontent.com/7489324/161303203-3333c67f-e52d-414b-a508-ee01940d514b.png)

**Cat**
![image](https://user-images.githubusercontent.com/7489324/161303277-e938b26e-9c9f-4b6c-823c-f4ba6fb1bbcb.png)

**Comment by DocGreenRob** [comment]
@danielcweber  Ok, sorry about missing that. Here is a link to the Method in my code that is failing. I have checked it into a Git repo.

https://github.com/DocGreenRob/exram/blob/575aa965db87b0541f72a37aa3fa6e520989ad59/src/CDM.Branch.DataAccess/GenericRepository.cs#L103

**Comment by DocGreenRob** [comment]
@danielcweber the repro repo link is above. The company I am contracting for would like to use this library if we can accomplish some basic things. Your assistance is highly needed!

**Comment by danielcweber** [comment]
I'm sorry, I won't deep dive into this whole complex project structure. The template asks for a minimal (!) repro that isolates the unexpected behaviour you experience. I don't have the time/resources to debug large 3rd party code for free. The behaviour you're seeing is most likely due to a misconfiguration of the graph model on your side. As for the highly needed assistance, we can discuss paid consulting options though: Just follow the email link on the Readme page.

Thanks for your understanding.

**Comment by DocGreenRob** [comment]
@danielcweber 

1. Pull down the repo
2. Add/Update your appsettings.json to point to a Graph DB that was created using your Gremlinq Examples project
3. Hit F5, and from the swagger page locate this route under:
- `Test Controller`
- `all/relationships/{relationshipName}`
- and the relationship name is "`person-owns-pet`"

and you will see the issue :-)

You will notice that I am using your "EXACT" same model. Now, I am working for a corporation that is publicly traded and they have chosen to use Cosmos Graph. I'm new, but I rather work with your client than directly with "magic strings" and you have done a LOT of great work!

I'm trying to get the engineers to adopt your code. Please help. (could be big for you if we co-sign on your stuff)

I have sent ALL screenshots of EVERYTHING! Even the Models...

Maybe if you can help me with my [other bug (unable to run the solution](https://github.com/ExRam/ExRam.Gremlinq/issues/608)) I would be able to figure out what's going on and create a PR if needed :-) 

However I/we are willing to pay for assistance, but can I do some basic stuff first?

**Comment by danielcweber** [comment]
For the ExRam.Gremlinq project not building, I cannot reproduce. Everything builds fine in VS 2022 and on the build server.

In your sample code, the only configuration of a GraphModel is, for whatever reason, commented out and reads

```
GraphModel
    .FromBaseTypes<Vertex, Edge>(lookup => lookup
        .IncludeAssembliesOfBaseTypes())
```

Gremlinq has no ability to lookup all the Pet-derived classes when it only considers the assembly of Vertex and Edge, which are not in the same assembly as Pet or anything else, as far as I can see. There's a method to include more assemblies.

**Comment by DocGreenRob** [comment]
Thanks very much my friend @danielcweber !

**Comment by DocGreenRob** [comment]
@danielcweber maybe this is a stupid question. But here's what happened.
1. Your sample soltuion - the examples - wire up the `Program.cs` with creating a `gremlinQuerySource` and then using it like `await new Logic(gremlinQuerySource, Console.Out).Run();` [As shown in the Gremlinq Examples.](https://github.com/ExRam/ExRam.Gremlinq.Samples/blob/b6ac9e29d95df4af677ade1e7a86a46d629e815c/ExRam.Gremlinq.Samples.Console/Program.cs#L68)
2. So I'm creating a WebApi and wanted to wire it up. And it wasn't until I watched your video on CosmosDB Tv and saw you explain and add your connection string to the `appsettings.json` did it work and then I was like "aha" I don't need to wire up the `Program.cs` and everything worked fine.
3. Now I see you are right about the `IncludeAssembliesOfBaseTypes` but my question is how do I wire it up? Given that I'm not trying to execute `Logic` but actually want to run my application. Do you have an example or can you give some simple instruction?

**Comment by danielcweber** [comment]
For an ASP WebApi, you're probably better off with the [other sample app](https://github.com/ExRam/ExRam.Gremlinq.Samples/tree/b6ac9e29d95df4af677ade1e7a86a46d629e815c/ExRam.Gremlinq.Samples.AspNet).

**Comment by DocGreenRob** [comment]
After looking at it, it seems that you actually don't show the usage of the `IncludeAssembliesOfBaseTypes` in the `ExRam.Gremlinq.Samples.AspNet`. Can you please elaborate? Really need this simply to get `Dog` and `Cat` of `Pet`.

**Comment by danielcweber** [comment]
F12 into the [IAssemblyLookupBuilder](https://github.com/ExRam/ExRam.Gremlinq/blob/439fb025c386b1487487251f08129fe2518dd36e/src/ExRam.Gremlinq.Core/Models/IAssemblyLookupBuilder.cs) interface that you are dealing with here. It's all there.

**Comment by danielcweber** [comment]
What you want to do is `IncludeAssembliesOfBaseTypes` for the base vertex and edge types you set the model up with, and use  `IncludeAssemblies` for the assemblies that Cat, Dog, etc. are in. Because they are in different assemblies. It's a fluent interface, you can call both. The usage of `IncludeAssembliesOfBaseTypes` is in the samples and you even copy-pasted it in your own code.

**Comment by danielcweber** [comment]
BTW, you can use all the Console-App-configuration in the WebApp-configuration. Just use ConfigureEnvironment on GremlinqSetup and configure things manually, instead of the UseCosmosDB-convenience-method. It's all the same from there.

**Comment by DocGreenRob** [comment]
@danielcweber (just read your replies, I really really appreciate your time!) but we can just solve this at the time of our consultation. Hopefully you have some time today! (emailing you now...)

**Comment by DocGreenRob** [comment]
@danielcweber I emailed you, but here you go. I have 3 issues. Now I'm trying to figure out how to implement `hasid(..)`. 

[Here are my issues.](https://github.com/DocGreenRob/exram/blob/main/README.md)

You will see I have an issue with `Upsert` as of now I have it looking like:

````
var destinationVertexObject = await _gremlinQuerySource
                .V<V2>().Where(vertex2Filter)
                .Fold()
                .Coalesce(
                    __ => __.Unfold(),
                    __ => __.AddV<V1>(v1)).FirstAsync();

            var destinationVertex = (dynamic)destinationVertexObject;
            object id = destinationVertex.id;

            var query = _gremlinQuerySource
                .V<V1>().Where(vertexFilter)
                .Fold()
                .Coalesce(
                    __ => __.Unfold(),
                    __ => __.AddV<V1>(v1))
                .InE<E1>().Where(x => x.OutV<V1>().Where(y => y.Id == id))
                .Fold()
                .Coalesce(
                    __ => __.Unfold(),
                    __ => __.AddE<E1>(e1))
                .Debug();
````

and I'm able to get the following gremlin query

````
V()
	.hasLabel('Person').has('Name','Robert Green').has('Age',42)
	.fold()
		.coalesce(
			__.unfold(),
			__.addV('Person').property(single,'Age',42).property(single,'Name','Robert Green').property(list,'PhoneNumbers','123-456-7890').property(single,'pk','Person')
			)
		.inE('Created').where(__.outV().hasLabel('Person').has(id,'321bafaa-efd3-451e-94c5-4b13fdd9b172'))
	.fold()
		.coalesce(
			__.unfold(),
			__.addE('Created').property('CreationDateTimeUtc','4/11/2022 3:16:52 PM').property('EffectiveEndDateTimeUtc','9999-12-31T23:59:59.9999999Z').property('EffectiveStartDateTimeUtc','0001-01-01T00:00:00.0000001Z').property('LastUpdateDateTimeUtc','4/11/2022 3:16:52 PM')
````

**Comment by DocGreenRob** [comment]
@danielcweber  Update: (haven't checked this in yet)

````
public async Task UpsertVertexesAndEdgeAsync(
            Expression<Func<V1, bool>> vertexFilter,
            V1 v1,
            Expression<Func<V2, bool>> vertex2Filter,
            V2 v2,
            E1 e1,
            Expression<Func<E1, bool>> edgeFilter)
        {
            // if V2 (destination vertex) doesn't exist, create it
            var destinationVertexObject = await _gremlinQuerySource
                .V<V2>().Where(vertex2Filter)
                .Fold()
                .Coalesce(
                    __ => __.Unfold(),
                    __ => __.AddV<V2>(v2)).FirstAsync();

            var query = _gremlinQuerySource
                .V<V1>().Where(vertexFilter)
                .Fold()
                .Coalesce(
                    __ => __.Unfold(),
                    __ => __.AddV<V1>(v1)
                    )
                .InE<E1>().Where(x => x.OutV<V1>().Where(y => y.Id == destinationVertexObject.Id)).Where(edgeFilter)
                .Fold()
                .Coalesce(
                    __ => __.Unfold(),
                    __ => __.AddE<E1>(e1).From<V2>(new StepLabel<V2>())
                    )
                .Debug();
        }
````

results:

````
V()
	.hasLabel('Person').has('Name','Robert Green').has('Age',42)
	.fold()
		.coalesce(
			__.unfold(),
			__.addV('Person').property(single,'Age',42).property(single,'Name','Robert Green').property(list,'PhoneNumbers','123-456-7890').property(single,'pk','Person')
			)
		.inE('Created').where(__.outV().hasLabel('Person').has(id,'321bafaa-efd3-451e-94c5-4b13fdd9b172')).hasNot('Purpose')
	.fold()
		.coalesce(
			__.unfold(),
			__.addE('Created').property('CreationDateTimeUtc','4/11/2022 5:17:34 PM').property('EffectiveEndDateTimeUtc','9999-12-31T23:59:59.9999999Z').property('EffectiveStartDateTimeUtc','0001-01-01T00:00:00.0000001Z').property('LastUpdateDateTimeUtc','4/11/2022 5:17:34 PM').from('l1')
````
1. Why do I get `hasNot` when I append `edgeFilter`? (see `hasNot('Purpose')`)
2. In the final piece I'm trying to add to the final `addE()` to a new Vertex `V2` so I used `AddE<E1>(e1).From<V2>(StepLabel...)` couldn't figure out how to use the `Func` overload. But what I need is: `.from(g.V(['Pet', '123-456-7890-blah-blah-guid'])`.

How can I build up `.from(g.V(['Pet', '123-456-7890-blah-blah-guid'])`

**Comment by danielcweber** [comment]
hasNot is usually the translation result of Where(x => x == null)

**Comment by DocGreenRob** [comment]
yes, I just fixed that, lol:

````
[
  {
    "cat": {
      "name": "Garfield",
      "age": 50
    },
    "dog": {
      "name": "Odis",
      "age": 40
    },
    "person": {
      "name": "Robert Green",
      "age": 42,
      "phoneNumbers": [
        "123-456-7890"
      ]
    },
    "software": {
      "name": "HomeaZZon",
      "language": 3,
      "purpose": "PersonalProject"
    }
  }
]
````

forgot to populate `Purpose` of `Software` :-)

**Comment by DocGreenRob** [comment]
`.has('Purpose','PersonalProject')` @danielcweber  works as expected, now just need the last `From` part... pleaseeeeeeee

**Comment by DocGreenRob** [comment]
@danielcweber simply... how can I use this `Vertex` in the `From`?

![image](https://user-images.githubusercontent.com/7489324/162803601-3bb60f9d-8f96-488e-a8c3-cb22909d124d.png)

**Comment by DocGreenRob** [comment]
ok, we resolved that issue and now this is my only last issue. I really need to fix why I can't get `Cat` and `Dog` when I say `Pet`. It is very powerful if I am able to do so! @danielcweber you have the repo access.

**Comment by DocGreenRob** [comment]
@danielcweber the original issue for this bug: https://github.com/ExRam/ExRam.Gremlinq/issues/609#issuecomment-1087613150

(we got a little off trail on this one)

**Comment by DocGreenRob** [comment]
https://user-images.githubusercontent.com/7489324/161302552-09f38fa4-5a46-4d07-9a13-1d94280e42c9.png

**Comment by danielcweber** [comment]
I think I already proposed a possible fix [here](https://github.com/DocGreenRob/exram/issues/3#issuecomment-1098152929) that has yet to make it into the code.

**Comment by DocGreenRob** [comment]
@danielcweber I have replied [here](https://github.com/DocGreenRob/exram/issues/3#issuecomment-1104352681).
