### ISSUE TITLE
Update multi properties on  CosmosDb  Graph .

### ISSUE THREAD

**Issue by iAmBipinPaul** [ExRam/ExRam.Gremlinq#61]
> First of all. This is really an awesome library and Thank you.

**Describe the bug**
While updating multi properties it keeps the old value and adds new one also.

**Expected behavior**
All old value should be removed and it should keep only new value.

**Version information**
```
<PackageReference Include="ExRam.Gremlinq.Providers.CosmosDb" Version="8.0.0-preview-0294" />    
```
*User.cs*
```csharp
  public class User: Vertex
    { 
        public string Name { get; set; }
        public SubscriptionMode[] SubscriptionModes { get; set; }
    }
```
```csharp
    public enum SubscriptionMode
    {
         Free = 1,
         Paid= 2  
    }
```

Update statement 

```csharp
var  result =
                   await _g.V<User>(user.Id)
                    .Property(x => x.Name, user.Name)
                    .Property(x => x.SubscriptionModes, user.SubscriptionModes)
                   .FirstAsync(cts);
```

**Comment by danielcweber** [comment]
I'm currently not sure whether this is actually desired behaviour. I'll have a look into this. In the meantime, you can drop all the properties in a sideeffect: 

`....SideEffect(__ => __.Properties(x => x..).Drop())`

**Comment by chrisc-hocketstick** [comment]
Any news on this? having to completely update an item each time a single of it's properties are changed is rather a nuisance...inefficient since one need to get all the values to re-assert after the drop

**Comment by danielcweber** [comment]
I don't agree that "All old value should be removed and it should keep only new value." is the desired/expected behaviour. After all, how would you then add a value to a multi-property if that's what you intend? Dropping the multi-property is currently the way to go unless a different clean viable solution presents itself.
