### ISSUE TITLE
How to Include cosmos-db system properties.

### ISSUE THREAD

**Issue by iAmBipinPaul** [ExRam/ExRam.Gremlinq#63]
Hi !
How can I write query in way that it will include cosmos-db system properties ?

This is the way I'm connecting to  cosmos-db.

```csharp
_g = g .ConfigureEnvironment(env => env
                    .UseModel(GraphModel.FromBaseTypes<Vertex, Edge>(lookup => lookup
                        .IncludeAssembliesOfBaseTypes()))
                    .UseCosmosDb(builder => builder
                        .At(uri, database, graphName)
                        .AuthenticateBy(authKey)));
```

Current query to get `User` vertex which does not return system properties.
```csharp
   await _g.V<User>();
```

Raw gremlin query that returns `_ts` (system property) from `CosmosDb`

```
g.withStrategies(ProjectionStrategy.build().IncludeSystemProperties('_ts').create())
.V().hasLabel("User")
```
Thank you !

**Comment by danielcweber** [comment]
Unfortunately currently not possible.

**Comment by iAmBipinPaul** [comment]
Okay !
Thank you for your response.

**Comment by jurkrit** [comment]
Is there any chance in in getting this included?

**Comment by danielcweber** [comment]
@iAmBipinPaul, @jurkrit Please have a look at https://docs.gremlinq.net/extensions/, specifically at the Gremlin.Extensions.Strategies package.
