### ISSUE TITLE
Would like to be able to log the StatusAttributes in the response from Cosmos

### ISSUE THREAD

**Issue by GarethJames** [ExRam/ExRam.Gremlinq#64]
We are finding it difficult to associated analytics in CosmosDb with the queries that ran. Responses from Cosmos return StatusAttributes which include the RU cost of a query; this is available using Gremlin.Net. The WebSocket implementation of the Executor in Gremlinq returns the objects from the response, but we can't find a way of accessing the StatusAttributes.

It would be nice for QueryLoggingOptions to include an additional option such as "**QueryAndParametersWithStatusAttributes**" and for the Executor to log StatusAttributes if configured to do so.

Alternatively, an extensibility point could be made available for us to run our own code before returning objects from the response.

**Comment by danielcweber** [comment]
This has finally been made possible through an extension library:

https://docs.gremlinq.net/extensions/diagnostics/
