### ISSUE TITLE
.Property() is broken

### ISSUE THREAD

**Issue by DocGreenRob** [ExRam/ExRam.Gremlinq#640]
**Describe the bug**
When I call the `.Property()` extension on an `IVertexGremlinQuery` the expectation is that it should add that property to the query. And it works in some cases. However if I have a list of properties that I want to add to the query and in a loop I call `Property('x', 'val x')` it does nothing. However if, outside the loop I say: `Property('a', 'val 1')` it works properly.

**Expected behavior**

**Version information**
Tell us which version of ExRam.Gremlinq you are using.

**Minimal working example**
````
private IVertexGremlinQuery<V1> GetProperties(V1 vertex, IVertexGremlinQuery<V1> vertexQuery)
        {
            var vertexType = vertex.GetType();
            var vertexProperties = vertexType.GetProperties();

            //foreach (var propertyInfo in vertexProperties)
            //{
            //    var key = propertyInfo.Name;
            //    if (key == "Id" || key == "Label")
            //    {
            //        continue;
            //    }
            //    var value = propertyInfo.GetValue(vertex);
            //}

            for (var i = 0; i < 3; i++)
            {
                vertexQuery.Property("a"+i.ToString(),"d"+i.ToString());
            }

            return vertexQuery.Property("a","d");
        }
````

The output is `[gremlinQuery].property(single, 'a', 'd')` but the expected output should be:
`[gremlinQuery].property(single, 'a0', 'd0').property(single, 'a1', 'd1').property(single, 'a2', 'd2')`

- a link to GitHub repository containing a minimal executable project
[https://github.com/DocGreenRob/exram](https://github.com/DocGreenRob/exram)

To Reproduce:
1. Get latest
2. F5 (run)
3. Route: `TestData => HttpPost`
4. Use this payload:
````
[
  {
    "cat": {
      "name": "Garfield",
      "age": 50
    },
    "dog": {
      "name": "Odis",
      "age": 40
    },
    "person": {
      "name": "Robert Green",
      "age": 42,
      "phoneNumbers": [
        "123-456-7890"
      ],
      "favoriteSport": "Football"
    },
    "software": {
      "name": "HomeaZZon",
      "language": 3,
      "purpose": "PersonalProject",
      "purpose2": "PersonalProject2"
    }
  }
]
````

you will see the Gremlin query as the result. But it should append the above `.property(..)` but it doesn't.

**Comment by danielcweber** [comment]
You call `property`, then throw away the result. Don't. Everything is immutable in Gremlinq.

Also, just because there's caveats like this, doesn't immediately mean something is 'broken'.

**Comment by DocGreenRob** [comment]
@danielcweber what do you mean? If I hard code `.Property("a", "b").Property("c","d")` it will render the query `x.property('a','b').property('c','d')`. Therefore my loop should append `.Property(..)` to `vertexQuery` in my method. What am I "throwing away"? and how am I doing it?

**Comment by DocGreenRob** [comment]
my true code loops and in each loop appends `vertexQuery.Property[key], [value])` and then at the end I simply return `vertexQuery` but I never get the appended properties. Only if I hard code does it work.

**Comment by DocGreenRob** [comment]
closing was able to use `.Update()` didn't know you had that extension method. Does exactly what I need.

**Comment by danielcweber** [comment]
> my true code loops and in each loop appends `vertexQuery.Property[key], [value])` and then at the end I simply return `vertexQuery` but I never get the appended properties. Only if I hard code does it work.

That is because `vertexQuery` never changes. Everything in Gremlinq is immutable like I said. If it works when you chain calls, and it doesn't work in a loop, then it's because you didn't chain the calls, thus effectively throwing away the result (like I already pointed out). You can chain the calls in a loop by storing the result of the call into the existing variable. Here is some example code for the loop body

`vertexQuery = vertexQuery.Property("a"+i.ToString(),"d"+i.ToString());`
