### ISSUE TITLE
Support F# Discriminated Unions

### ISSUE THREAD

**Issue by xperiandri** [ExRam/ExRam.Gremlinq#66]
**Is your feature request related to a problem? Please describe.**
I cannot use F# discriminated unions, in particular, single case unions as properties.

**Describe the solution you'd like**
Implement Gremlinq converted based on Newtonsoft's `DiscriminatedUnionConverter`

**Additional context**
``` F#
[<Struct>]
type DomainID<'t> = private DomainID of Guid

type UzantoID = DomainID<Uzanto>
and Uzanto =
    { [<JsonProperty("id")>]
      ID : UzantoID
      PhoneHash : SingleLineText<PhoneHash>
...
 ```

**Comment by xperiandri** [comment]
Maybe I don't understand the serialization mechanism or I cannot find a way to transform property value to Gremlinq supported type before serialization?

**Comment by danielcweber** [comment]
Not sure what you are proposing I'm afraid

**Comment by xperiandri** [comment]
Let's have a look at `DomainID` type which is a wrapper around `Guid`

``` C#
[Serializable, StructLayout(LayoutKind.Sequential, CharSet=CharSet.Auto, Size=1), Struct, 
public struct DomainID<t> : IEquatable<DomainID<t>>, IStructuralEquatable, IComparable<DomainID<t>>, IComparable, IStructuralComparable 
{
     internal Guid item;
     [CompilationMapping(SourceConstructFlags.UnionCase, 0)]
     internal static DomainID<t> NewDomainID(Guid item) =>
          new DomainID<t>(item);

     [CompilerGenerated, DebuggerNonUserCode]
     internal DomainID(Guid item)
     {
         this.item = item;
     }

     [CompilationMapping(SourceConstructFlags.Field, 0, 0), CompilerGenerated, DebuggerNonUserCode]
     internal Guid Item => this.item;
...
```
As you can see it is a wrapper struct that holds a single value and has phantom generic parameter to distinguish Id for different entities.
When saving it to Gremlin I need a mechanism to unwrap held value and when reading from Gremlin to wrap back.

**Comment by xperiandri** [comment]
How can Gremlinq be extended to support such a scenario?

**Comment by danielcweber** [comment]
You can see something similar [here](https://github.com/ExRam/ExRam.Gremlinq/blob/master/ExRam.Gremlinq.Core/GremlinQueryEnvironment.cs#L109) for TimeSpans-to-double and vice versa conversion. None of this has been released yet though.

**Comment by danielcweber** [comment]
The above scenario is possible with the latest preview, see comment above.

**Comment by xperiandri** [comment]
Looks good, thnaks!

**Comment by xperiandri** [comment]
@danielcweber could you point to the place where I can look at the sample now?
