### ISSUE TITLE
Question: Properties on Edges

### ISSUE THREAD

**Issue by chrisc-hocketstick** [ExRam/ExRam.Gremlinq#67]
**Not a bug** but is it possible to have properties/facets on edges? I see no example of doing so and in fact the code:
_await _g.V(vertex1.Id).AddE<Composes>().To(__ => __.V(vertex2.Id)).FirstAsync();_

(since AddE takes a type declaration, not an instance of that type) seems to preclude. 

If possible, an example of setting/querying by edge.property would be useful.

**Comment by iAmBipinPaul** [comment]
Hi @chrisc-hocketstick yes you can set properties on edge.
https://github.com/ExRam/ExRam.Gremlinq.Samples/blob/master/ExRam.Gremlinq.Samples/Model/Owns.cs
```csharp
 return await _g
                 .V(input.UserId)
                 .AddE<Subscribed>(new Subscribed
                 {
                    //edge properties goes here
                     DateTime= DateTime.UtcNow;
                 })
                 .To(__ => __
                     .V(input.PlanId))
                 .FirstAsync();
```

**Comment by danielcweber** [comment]
Check out the "Property" method, which mirrors native Gremlin's 'property' step. Also, in your development environment, try to F12 (if in Visual Studio) into the interface definitions and browse to see what's there.

**Comment by chrisc-hocketstick** [comment]
Hi there, thanks for the quick response. I think there is something missing from the above? I get an invalid operation exception. Both vertices have been saved to the graph successfully. 
Exception:

{System.InvalidOperationException: Operation is not valid due to the current state of the object.    at ExRam.Gremlinq.Core.GremlinQuery`6.GetPropertySteps(Type propertyType, Object key, Object value, Boolean allowExplicitCardinality)+MoveNext() in /home/vsts/work/1/s/ExRam.Gremlinq.Core/Queries/GremlinQuery.cs:line 310    at ExRam.Gremlinq.Core.GremlinQuery`6.AddOrUpdate(TElement element, Boolean add, Boolean allowExplicitCardinality) in /home/vsts/work/1/s/ExRam.Gremlinq.Core/Queries/GremlinQuery.cs:line 283    at ExRam.Gremlinq.Core.GremlinQuery`6.ExRam.Gremlinq.Core.IVertexGremlinQueryBase<TElement>.AddE[TEdge](TEdge edge) in /home/vsts/work/1/s/ExRam.Gremlinq.Core/Queries/GremlinQuery.explicit.cs:line 41    at HockeyStick.Graph.Models.CosmosDbGraphFactory.AddEmployedByE(VertexBase vertex1, VertexBase vertex2, EmployedBy employ) in /Users/christopher/Projects/ExRam.Gremlinq.Samples-master/Hockeystick.Graph/Models/Factory/CosmosDbGraphFactory.cs:line 241}

See attached code snippet. No fields have null values. Linkage works fine if I remove the edge object (employ in example). Also, as expected, if the object is created via _new_ as above.

![image](https://user-images.githubusercontent.com/63007080/80995096-b4f59800-8e0b-11ea-97d1-aad63a64a7b0.png)

**Comment by danielcweber** [comment]
I can't figure out anything from the image you posted (could you if you hadn't written it?). You might want to setup a complete minmal working example repository.

**Comment by chrisc-hocketstick** [comment]
Sorry, poorly documented. Removing a string[] from edge class' property list allowed it to be saved. Each element had a value, if that matters. I've deleted the post.
