### ISSUE TITLE
Support for IQueryable<T> 

### ISSUE THREAD

**Issue by iAmBipinPaul** [ExRam/ExRam.Gremlinq#68]

**Comment by danielcweber** [comment]
What's the point?

**Comment by iAmBipinPaul** [comment]
Hi , So I want to have paging, for that I have to return total count and list of page size data.
as of now I have to write same query two times in order to get the count and data.


```csharp

  return new PagedResult<User>
            {
                TotalCount = await _g.V<User>()
                    .Order(o => o.By(g => g.Name))
                    .Count().FirstOrDefaultAsync(),

                Items = await _g.V<User>()
                    .Order(o => o.By(g => g.Name))
                    .Limit(input.MaxResultCount + input.SkipCount)
                    .Skip(input.SkipCount)
            };
```

so If there will be support for IQueryable<T>, We can construct query  in multi stage.

```csharp
IQueryable<User> query =_g.V<User>()
                    .Order(o => o.By(g => g.Name));


return new PagedResult<User>
            {
                TotalCount = await query.Count().FirstOrDefaultAsync(),

                Items = await query.Limit(input.MaxResultCount + input.SkipCount)
                                             .Skip(input.SkipCount)
                                            .ToArrayAsync()
            };
```

Thank you !

**Comment by danielcweber** [comment]
This is pretty much how Gremlinq already works. Really no need to execute the query twice. Gremlinq queries can be reused and mutiple subqueries can be traversed throught the 'Project' operator.

````
var tuple = await _g.V<User>()
    .Order(o => o.By(g => g.Name))
    .Fold()
    .Project(p => p.ToTuple(
            __ => __.CountLocal(),
            __ => __.Unfold().Limit(input.MaxResultCount + input.SkipCount).Skip(input.SkipCount).Fold()))
````

Untested.

**Comment by iAmBipinPaul** [comment]
Hi , Thank you very much !
but I'm getting  error that  there is no overload for method `ToTuple` that takes two parameter.
```csharp
 var tuple = await _g.V<Person>()
                .Order(o => o.By(g => g.Name))
                .Fold()
                .Project(p => p.ToTuple(
                    __ => __.CountLocal(),
                    __ => __.Unfold()
                        .Limit(10)
                        .Skip(0).Fold()));
```
![image](https://user-images.githubusercontent.com/9201481/81404546-7e928280-9155-11ea-9158-bfd4b580b583.png)

**Comment by danielcweber** [comment]
I updated my comment above

**Comment by iAmBipinPaul** [comment]
Thank you it worked.
There is one comma and extra bracket at the last after removing  that it worked.
```
```

**Comment by iAmBipinPaul** [comment]
May be we should rename the issue.
as here is nothing to do with `IQueryable<T>`

**Comment by danielcweber** [comment]
Can this be closed? I'm sorry I still don't get where there is currently a shortcoming and how IQueryable would provide any solution.

**Comment by iAmBipinPaul** [comment]
H, sure this can be closed.
> I'm sorry I still don't get where there is currently a shortcoming and how IQueryable would provide any solution.

I just wanted to have same IQueryable that I can use two times but  I'm able to do this as you suggested so  It's all good now.
Thank you 
Sorry for the confusion 🙏
