### ISSUE TITLE
Logger not being passed to Executor

### ISSUE THREAD

**Issue by SyntaxUnknown** [ExRam/ExRam.Gremlinq#7]
I was looking to capture the log statements from the WebSocketGremlinQueryExecutor class, but I could never get those logging statements to show up.

I have constructed my graph source as follows:

```
var graph = g
                .WithLogger(_logger)
                .WithModel(GraphModel.Dynamic()
                .WithLowercaseLabels())
                .WithCosmosDbRemote(host, db, graph, key);
```

If you look at the code for WithCosmosDbRemote and WithRemote, neither of them pass the logger through to the optional logger param of WebSocketGremlinQueryExecutor.

My work around for now is to do the following:

```
var graph = g
                .WithLogger(_logger)
                .WithModel(GraphModel.Dynamic()
                .WithLowercaseLabels())
                .WithExecutor(new WebSocketGremlinQueryExecutor<CosmosDbGroovyGremlinQueryElementVisitor>(
                    new CosmosDbGremlinClient(
                    new CosmosDbGremlinServer(host, db, graph, key)),
                    new CosmosDbGraphsonSerializerFactory(), _logger));
```

I was looking at the code and it seems like there should be some way to get the logger that was created in "WithLogger" in the other extension methods, but I'm not sure how you'd like to expose that.

Thanks again!

**Comment by danielcweber** [comment]
Hi, thanks for using the library. I will get back to this issue on monday.

**Comment by danielcweber** [comment]
That's indeed tricky. One solution would be for the executor not to take the logger in the constructor but on execution. But I don't like the approach since it breaks good DI patterns.

Another solution is to expose the logger in `IConfigurableGremlinQuerySource` for `WithCosmosDbRemote` to pick up.

**Comment by danielcweber** [comment]
Maybe this issue is a strong case against this type of configuration. Probably, the current `With...` methods should just be extensions on DI containers (ASP.net core's IServiceCollection etc) to do proper DI.

**Comment by SyntaxUnknown** [comment]
I think the `With...` pattern is pretty nice. Again, back to Entity Framework, they do the same thing but they add another layer to it called the DbContext and there they expose a virtual method called `OnConfiguring`. 

I think it'd be pretty straightforward to just expose it in the `IConfigurableGremlinQuerySource` though. Maybe you could expose it as an `internal`?

**Comment by danielcweber** [comment]
There's no such thing as internal on interfaces. I think I might just expose it on IConfigurableGremlinQuerySource.

**Comment by danielcweber** [comment]
Could you have a look at 43ad97121360240d3eba90fcfef90ca26d8765c5 and whether it solves the issue.

**Comment by SyntaxUnknown** [comment]
Looks good! Thanks for the update!

**Comment by SyntaxUnknown** [comment]
Closing this one as it is working great now.
