### ISSUE TITLE
CosmosDB Properties

### ISSUE THREAD

**Issue by jurkrit** [ExRam/ExRam.Gremlinq#70]
With reference to #63 , is there any chance in getting this included?

**Comment by danielcweber** [comment]
Well, it could be done for a bytecode query, but I wouldn't currently know how to automatically convert all the strategies there are to their respective groovy representation. So at this time the answer is 'no', but given that CosmosDB will ultimately support Bytecode, there's a chance.

If you have a good idea - this is open source after all.

**Comment by jurkrit** [comment]
Cool thanks, I gave it a shot, but I think I am to "stupid", cant get it working .... :)

**Comment by danielcweber** [comment]
See #63.

**Comment by utillity** [comment]
so #63 and #70 are closed - will anyone ever work on this?

**Comment by danielcweber** [comment]
> so #63 and #70 are closed - will anyone ever work on this?

Will you?

**Comment by utillity** [comment]
I can offer my help. It's just interesting that in each ticket you point to the other and close it. So I don't know about you but from my experience things will not get done, if there is no task tracking it ;)
