### ISSUE TITLE
Support for records with only init properties without parameterless constructor

### ISSUE THREAD

**Issue by bCamba** [ExRam/ExRam.Gremlinq#706]
**Is your feature request related to a problem? Please describe.**
I am frustrated because I can't use records with init only properties as a vertex without also declaring a default parameterless constructor for vertices. If I try to do that when adding vertices I get **"Object reference not set to an instance of an object."** coming from Newtonsoft that is called within ExRam.Gremlinq.

**Describe the solution you'd like**
I want to be able to use records and classes with only init properties as a vertices without needing to declare a default parameterless constructor.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Consider sponsoring me**
I am sponsoring. This is a great project! Thank you for it.

**Comment by danielcweber** [comment]
Could you link to a minimal working solution that'll throw the NRE ?

**Comment by bCamba** [comment]
Yes, I added it to this repo https://github.com/bCamba/gremlinParameterlessPOC
While doing it I figured the problem was not what I described. It does work without a parameterless constructor. The problem happens because even though my constructor and my property are not nullables, Newtonsoft calls the constructor passing null and inside the constructor I try to call a method on that property and it fails

**Comment by danielcweber** [comment]
Yes, Gremlinq let's Newtonsoft first create the instance, then populate it. So better not use these constructorsm but only ever parameterless constructors.

**Comment by bCamba** [comment]
Yes this does make a lot of sense. Thanks!
