### ISSUE TITLE
Question: Expression Tree Support and Dynamic Query Scenarios

### ISSUE THREAD

**Issue by chris-hockeystickco** [ExRam/ExRam.Gremlinq#74]
Use Case:
Application doesn't know ahead of time what attributes on entities will be queried nor the operators between them. As such, these are dynamic queries that must be handled in code. 

Question:
Does Gremlinq support Expressions trees (as does Linq [https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/]) and create appropriate tinkerPop syntax or is there another means of handling queries whose predicates and operators are not known at compile time?

**Comment by danielcweber** [comment]
E.g. some `Where` overloads, among others, take expression parameters. Does this match your use case?

**Comment by haseebahmed7** [comment]
@danielcweber I think I'm facing the same problem. When dealing with C# IEnumerable types, you can turn them into IQueryable and then pass in string queries e.g. "SomeProperty eq 'My Name'" but I have not been able to do so with IVertexGremlinQuery... Maybe there is some way that I'm not familiar with?

**Comment by danielcweber** [comment]
I unfortunately still don't have a clue what this would look like in Gremlinq....or what the original issue is to begin with.

**Comment by haseebahmed7** [comment]
Lets say a user has the ability to send in a query string via API endpoint, which looks something like this:

```
string query = "PropertyA eq 'SomeValue' and PropertyB eq 'Another Value'"
```

Now in EF I'd do something like:

```
db.Set<SomeEntity>.AsQueryable().Where(query).ToList()
```

This would automatically return me Some Entities where PropertyA = Some Value and PropertyB = Another Value.

How would I do this with GremlinQ?

**Comment by danielcweber** [comment]
So you'd like to send in raw Gremlin ?

**Comment by danielcweber** [comment]
Or it's rather some new language construct?

**Comment by haseebahmed7** [comment]
@danielcweber Not gremlin but its  language construct pretty similar to what OData APIs use buy simpler version of it. Syntax is something like:

`PropertyName Operator Value` and you can combine multiple of these with Boolean operators. I'd check and get back to you but I think this is supported by default by C# Queryable types. There must be some name for it, I just dont know whats it formally called.

**Comment by haseebahmed7** [comment]
@danielcweber I figured it out! What I am referring to is [Dynamic Linq](https://dynamic-linq.net/) and doesn't have to do anything with GremlinQ or EF. Thank you for your time and hopefully this would help anyone else as well who stumbles upon this Issue :-)
