### ISSUE TITLE
Label property is not acknowledged on element types.

### ISSUE THREAD

**Issue by Cephei** [ExRam/ExRam.Gremlinq#75]
**Describe the bug**
I've tried to explore your sample project and unit tests. You have a `Label` property I've often seen on example vertex classes, but it's seemingly never used to override the default behavior (assigning the label based upon `Type` name.) Was this ever an intended feature?

**Expected behavior**
Allow elements to override the serialization of gremlin label.

**Version information**
8.0.0-preview-0586

**Minimal working example**
Just try putting the property on any type used as a vertex. (I have not tried edges)
```
public string Label { get; set; }
```

**Additional context**
My testing on this has been done against JanusGraph.

I've seen the ability to use `.ConfigureLabels((type, _) => ...)` to override labels, but since this is based upon type, it's not as powerful as allowing an instance to set the label dynamically. A nice feature might be to introduce a `ConfigureLabel<TElement>(Func<TElement, string> getLabelFunc)` or take into account a `Label` property.

**Comment by danielcweber** [comment]
Gremlinq is an object-graph-mapper. You may configure the actual label names per type, but you cannot set the label per entity. It would defeat the whole purpose of the object-graph-mapper, since....how is it supposed to ever find all vertices of a specific type then?
