### ISSUE TITLE
Configure IgnoreOnUpdate globally for specific shared property

### ISSUE THREAD

**Issue by andrewdmoreno** [ExRam/ExRam.Gremlinq#76]
The referenced example demonstrates ignoring a property on an update of a specific vertex type. I was able to get this to work, however, it looks like it requires you to call `ConfigureElement<MyVertexType>(...)` on the each vertex type specifically. For using with Cosmos Db all my Vertex types inherit from `IPartitionedVertex` that exposes a `partitionKey` property.  I have noticed that I need to omit the partition key when performing updates and I am trying to see if there is a way around having to call this for every single vertex type. 

I would like to be able to say something like the following

````
ConfigureElement<IPartitionedVertex>(t => t.IgnoreOnUpdate(v => v.PartitionKey))
````

or something equivalent where I don't need to do this for every single vertex type. If there is some way to accomplish this would be really helpful.

Have a look at [this unit test](https://github.com/ExRam/ExRam.Gremlinq/blob/55e374cb55cce02280510d974953026756a0bb95/ExRam.Gremlinq.Core.Tests/GroovySerializationTest.cs#L2297). It should give you some direction on how to achieve what you need.

_Originally posted by @danielcweber in https://github.com/ExRam/ExRam.Gremlinq/issues/52#issuecomment-597011202_

**Comment by andrewdmoreno** [comment]
I have tested with an abstract base class as opposed to an interface and I believe this behaves the way I was expecting.

**Comment by danielcweber** [comment]
I'll update the samples project accordingly. It only works with a base class today, not with interfaces.
