### ISSUE TITLE
Gremlin Query Compilation Error when using CosmosDB

### ISSUE THREAD

**Issue by nilshedstrom** [ExRam/ExRam.Gremlinq#78]
**Describe the bug**
I have written the following code using the code based on the data in Exram.Gremlinq.Samples.

```
        private async Task My_Query()
        {
            //Check if the pet Charlie has owner which is older than him but not more than 30 years older
            var pet = await _g
                .V<Pet>().Where(p => p.Name.Value == "Charlie").Limit(1)
                .Project(x => 
                    x.ToDynamic()
                        .By("petAge", pet => pet.Age)
                        .By("ownerMaxAge", pet => pet.Values(p => p.Age).Inject(30).Sum())
                        .By("ownerAge", pet => pet.In<Owns>().OfType<Person>().Values(p => p.Age)))
                .Cast<Result>().Where(GetFilterExpression()).ToArrayAsync();
        }

        private static Expression<Func<Result, bool>> GetFilterExpression()
        {
            return result => result.ownerAge > result.petAge && result.ownerAge <= result.ownerMaxAge;
        }

        internal class Result
        {
            public long ownerAge;
            public long petAge;
            public long ownerMaxAge;
        }
```
I am using Azure Cosmos Emulator (but the results are the same when running similar queries in an Azure instance of CosmosDB).

When I run the code I get the following exception
```
fail: Queries[0]
      Error executing Gremlin query V().hasLabel(_a, _b, _c).has(_d, _e).limit(_f).project(_g, _h, _i).by(__.in(_j).hasLabel(_k).values(_l)).by(__.values(_l).inject(_m).sum()).by(_l).as(_n).where(gt(_n)).by(_g).by(_i).as(_o).where(lte(_o)).by(_g).by(_h):
      Gremlin.Net.Driver.Exceptions.ResponseException: ScriptEvaluationError:

ActivityId : 43675d61-507c-4b86-b1d0-edd9cdfe27fa
ExceptionType : GraphCompileException
ExceptionMessage :
        Gremlin Query Compilation Error: Column reference R_6["ownerAge"] cannot be located in the raw records in the current execution pipeline.
Source : Microsoft.Azure.Cosmos.Gremlin.Core
        GremlinRequestId : 43675d61-507c-4b86-b1d0-edd9cdfe27fa
        Context : graphcompute
        Scope : graphstg-phyplan
        GraphInterOpStatusCode : QuerySyntaxError
        HResult : 0x80131500

         at Gremlin.Net.Driver.Messages.ResponseStatusExtensions.ThrowIfStatusIndicatesError(ResponseStatus status) in /home/smallette/git/apache/tinkerpop/gremlin-dotnet/src/Gremlin.Net/Driver/Messages/ResponseStatus.cs:line 47
         at Gremlin.Net.Driver.Connection.TryParseResponseMessage(ResponseMessage`1 receivedMsg) in /home/smallette/git/apache/tinkerpop/gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs:line 137
         at Gremlin.Net.Driver.Connection.Parse(Byte[] received) in /home/smallette/git/apache/tinkerpop/gremlin-dotnet/src/Gremlin.Net/Driver/Connection.cs:line 123
      --- End of stack trace from previous location where exception was thrown ---
         at Gremlin.Net.Driver.ProxyConnection.SubmitAsync[T](RequestMessage requestMessage)
         at Gremlin.Net.Driver.GremlinClient.SubmitAsync[T](RequestMessage requestMessage)
         at Gremlin.Net.Driver.GremlinClientExtensions.SubmitAsync[T](IGremlinClient gremlinClient, String requestScript, Dictionary`2 bindings)
         at ExRam.Gremlinq.Core.GremlinQueryEnvironmentExtensions.WebSocketGremlinQueryExecutor.<>c__DisplayClass6_0.<<Execute>g__Core|0>d.MoveNext() in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Providers.WebSocket/GremlinQueryEnvironmentExtensions.cs:line 60
```

**Expected behavior**
I expect my code not to throw an exception and return one item in the pet array (since Charlie is 2 and the owner is 32).

If the code is not supposed to work with CosmosDB please give me an example on how to write the query in a way that will work with CosmosDB.

**Version information**
ExRam.Gremlinq.Providers.CosmosDb 8.0.0-preview-0707

**Minimal working example**
https://github.com/nilshedstrom/ExRam.Gremlinq.Issue78

**Additional context**
After experimenting with raw gremlin queries I found that replacing the last where-statement with
```
where('ownerAge',gt('petAge')).where('ownerAge',lte('ownerMaxAge'))
```
will work with CosmosDB and return the expected result.
If I could somehow add this gremlin code to my c# query that would be a workaround but not as nice as being able to express it in C#.

**Comment by danielcweber** [comment]
The result from the project operator simply can't be cast to Result. For Gremlin, it's a stream of maps (or dictionaries in C# lingo). You can't apply the GetFilterExpression filter on it thus.

**Comment by danielcweber** [comment]
Try something like

            var pet = await _g
                .V<Pet>().Where(p => p.Name.Value == "Charlie").Limit(1)
                .As((pet, __) => __
                   .In<Owns>().OfType<Person>().Values(p => p.Age).As((ownerAge, __ =>
                       .Select(pet).Values(p => p.Age).Union(__ => __.Identity(), __ => __.Constant(30)).Sum().As((ownerMaxAge, __ =>
                           __ => __.Select(pet).Where(ownerMaxAge.Value <= ownerAge.Value)

It might not compile right away but you get the idea. Basically I would collect the things I need into step labels scopes (with As), then do a final Where operator on these.

**Comment by nilshedstrom** [comment]
So is there a way to express this query in c# that works with CosmosDb?
The reason i use projection is so that I can use .Inject(30).Sum() to calculate ownerMaxAge.

**Comment by danielcweber** [comment]
Don't use Inject, it doesn't behave as you think and there's differences in behaviour from the reference Gremlin implementation. See if the above answer works for you.

Otherwise, you should post a sample project (as requested in the issue template).

**Comment by nilshedstrom** [comment]
Example code available on https://github.com/nilshedstrom/ExRam.Gremlinq.Issue78
Your suggestion did not work because sum is a [reducing barrier step](http://kelvinlawrence.net/book/PracticalGremlin.html#rbarriers) and it will cause the database to forget the values stored in ownerAge and pet

**Comment by danielcweber** [comment]
Please allow me write access to the repo. Much easier than filing a pull request.

**Comment by danielcweber** [comment]
Nevermind, I opened a pull request. The query should do its job now.

It would be super awesome if you could include your example into the ExRam.Gremlinq.Samples project, along with some Console output (like the other examples) and provide a pull request for that.
