### ISSUE TITLE
Implement PropertyNamingAttribute

### ISSUE THREAD

**Issue by mkallsgard** [ExRam/ExRam.Gremlinq#79]
When using Gremlinq for querying the Vertices/edges must have Property names matching the model (name/casing).

is it possible/could a feature be added, where the lib either uses a JsonProperty Attribute or implements a Gremlinq Attribute, which indicates the correct name of a property in the Graph?

a simple example of usage is the Cosmos Graph Data explorer in the Azure Portal. This UI tool expects the property "name" to display in the property pane and on the graph vertices. 
When using "name" in the model combined with standard c# naming convention MyClass.Name the query g.V(Myclass).Where(mc => mc.Name == "someName") won't find any result.

**Comment by danielcweber** [comment]
Configure your GraphModel [like shown here](https://github.com/ExRam/ExRam.Gremlinq/blob/main/ExRam.Gremlinq.Core.Tests/GraphModelTest.cs#L156).

**Comment by mkallsgard** [comment]
I'm currently looking into adding Ontology context data into my graph. would it be possible to map something like "rdfs:comment" as property name?

**Comment by danielcweber** [comment]
You can configure a lot in `ConfigureMemberMetadata` (see previous answer). Configuring a name like you proposed should be possible given the db provider supports such naming.
