### ISSUE TITLE
Add Upsert<TVertex>() Shortcut Method

### ISSUE THREAD

**Issue by evo-terren** [ExRam/ExRam.Gremlinq#800]
**Is your feature request related to a problem? Please describe.**
I would like to perform an "upsert" and am pretty sure the best way to do so is according to the [Tinkerpop community's recommended pattern](https://stackoverflow.com/questions/49758417/cosmosdb-graph-upsert-query-pattern/49758568#49758568).  Using ExRam, the best way I can figure out to adhere to the pattern looks something like this:

```
g.V<MyVertexType>(myVertexInstance.Id)
  .Fold()
  .Coalesce(
    _ => _.Unfold().Update(myVertexInstance),
    _ => _.AddV(myVertexInstance)
  );
```

However, this results in duplicate `property(...)` statements (one for `Update()` and one for `AddV()`), which makes for an extremely long final gremlin command if you have several properties defined on your vertex objects; I'd prefer to have an optimized gremlin command, if possible.

For example, given a simplified vertex object:

```
public class Vertex
{
  public string Id { get; set; }
  public string Label { get; set; }
  public string SomeProperty { get; set; }
}

...

var myVertexInstance = new Vertex { Id = "my-vertex", SomeProperty = "some value" };
```

The above code produces the following gremlin command:

```
g.V().has('id', 'my-vertex').hasLabel('Vertex')
  .fold()
  .coalesce(
     _.unfold().sideEffect(properties('SomeProperty').drop()).property('SomeProperty', 'some value'),
     _.addV('Vertex').property('id', 'my-vertex').property('SomeProperty', 'some value')
  )
```

(Note the duplicate `property('SomeProperty', 'some value')`). I would prefer the following final gremlin command:

```
g.V().has('id', 'my-vertex').hasLabel('Vertex')
  .fold()
  .coalesce(
     _.unfold().sideEffect(properties('SomeProperty').drop()),
     _.addV('Vertex').property('id', 'my-vertex')
  ).property('SomeProperty', 'some value')
```

**Describe the solution you'd like**
I would like the library to expose a new `Upsert<TElement>(TElement e)` method that produces the optimized query result according to Tinkerpop's preferred pattern for both edges and vertices.

**Describe alternatives you've considered**
I have attempted to use the `AsAdmin()` "mode" of building queries, but this seemed to lead me down a dark and frustrating path. For example, I attempted something along these lines:

```
g.V<MyVertexType>(myVertexInstance.Id)
  .Fold()
  .Coalesce(
     _ => _.Unfold(),
     _ => _.AsAdmin().AddStep<IVertexGremlinQuery<MyVertexType>>(new AddVStep("Vertex"))
               .AsAdmin().AddStep<IVertexGremlinQuery<MyVertexType>>(new PropertyStep.ByKeyStep(new Key("id"), "my-vertex"))
  ).Update(myVertexInstance);
```

(Feel free to let me know if I'm using `AsAdmin()` incorrectly.) However, the problem with this approach (at least while using Cosmos Db as my underlying graph provider), is with the call to `Update()` as it seems to remove all user-defined properties on newly created vertices. I learned the hard way that if you perform the following raw gremlin command in a Cosmos Db instance:

```
g.addV('vertex')
  .property('id', 'myid')
  .property('partitionKey', 'mypartitionkey')
  .sideEffect(__.properties('someProperty').drop())
  .property('someProperty', 'some-value')
```

The resulting vertex will be missing any user-defined properties as your result will look like this:

```
[
  {
    "id": "myid",
    "label": "vertex",
    "type": "vertex",
    "properties": {
      "partitionKey": [
        {
          "id": "myid|partitionKey",
          "value": "myid"
        }
      ]
    }
  }
]
```

I assume this somehow occurs due to the call to `drop()` (seems like a bug to me, but who knows).

**Additional context**
One challenge with the full upsert pattern (starting from 'g') is that it assumes `g.V('some-label').has('id', 'some-id')` is all you need to define before performing the upsert. However, Cosmos Db consumers, for example, will almost certainly prefer to specify a partition key first due to performance gains. Therefore, I recommend this method being added to the `IVertexGremlinQueryBase<TElement>` interface over others (say, the `IStartGremlinQuery`) to give full flexibility for its usage. This will also keep it inline with the existing `Update()` shortcut method.

To fully optimize the resulting command, the implementation will need to take into consideration the properties that are ignored on add/update and place them in their proper place in the final command.

The call to drop properties should only be used within the "update" part of the upsert.

**Consider sponsoring me**
I will ask my company if they would be willing to sponsor you.

**Comment by evo-terren** [comment]
I'm still interested in this feature. Is this something you would at least accept a pull request on?

**Comment by danielcweber** [comment]
I am not so sure this kind of composite operator extensions should go into the core library. I could imagine a separate extension project for community provided convenience extensions like this. Maybe you'd be interested in creating and maintaining such an extension repo?

**Comment by DocGreenRob** [comment]
Here's how I solved the same: This Upsert takes 2 Vertexes and 1 Edge.

```
public async Task<string> UpsertVertexesAndEdgeAsync(Expression<Func<V1, bool>> vertexFilter,
						V1 v1,
						Expression<Func<V2, bool>> vertex2Filter,
						V2 v2,
						E1 e1,
						Expression<Func<E1, bool>> edgeFilter)
		{
			Stopwatch stopWatch = new Stopwatch();
			stopWatch.Start();

			var stepLabel = new StepLabel<V1>();

			var query = _gremlinQuerySource
										.V<V1>().Where(vertexFilter)
										.Fold()
										.Coalesce(
											__ => __.Unfold().Update(v1),
											__ => __.AddV<V1>(v1)
											)
										.As(stepLabel)
										.V<V2>().Where(vertex2Filter)
										.Fold()
										.Coalesce(
											__ => __.Unfold().Update(v2),
											__ => __.AddV<V2>(v2)
											)
										.Coalesce(
											__ => __.InE<E1>().Where(edgeFilter).Update(e1),
											__ => __.AddE<E1>(e1).From(stepLabel)
											)
										.Debug();

			var gremlinDebug = JsonConvert.DeserializeObject<GremlinDebug>(query);
			var gremlinDebugScript = gremlinDebug.Script;
			var updatedGremlinDebugScript = gremlinDebugScript.Replace("as('l1')", "store('l1')");
			var finaGremlinlQuery = updatedGremlinDebugScript.Replace("from('l1')", "from(select('l1').unfold())");
			finaGremlinlQuery = $"g.{finaGremlinlQuery}";

			ResultSet<dynamic> results = _gremlinClient.SubmitAsync<dynamic>(finaGremlinlQuery).Result;
			var requestCharge = (JsonElement)results.StatusAttributes["x-ms-request-charge"];

			stopWatch.Stop();

			TimeSpan ts = stopWatch.Elapsed;
			string elapsedTime = String.Format("{0:00}:{1:00}:{2:00}.{3:00}",
																	ts.Hours, 
																	ts.Minutes, 
																	ts.Seconds,
																	ts.Milliseconds / 10);

			var customEvents = new Dictionary<string, string>();
			customEvents.Add("GremlinQuery", finaGremlinlQuery);
			customEvents.Add("ElapsedTime", elapsedTime.ToString());
			customEvents.Add("VertexesAndEdge", $"{typeof(V1).Name} > [{typeof(E1).Name}] > {typeof(V2).Name}");
			customEvents.Add("RequestCharge", requestCharge.GetRawText());

			_telemetryClient.TrackEvent("Upsert Vertexes & Edge Metrics", customEvents);

			return $"{finaGremlinlQuery} -------------> {elapsedTime} <------------- {typeof(V1).Name} > [{typeof(E1).Name}] > {typeof(V2).Name} :: ru = ({requestCharge.GetRawText()}) ";
		}
```

**Comment by danielcweber** [comment]
@evo-terren I indeed didn't pay too much attention to the new mergeE and mergeV steps introduced in v3.6. Of course I'd be accepting PRs. I'm not sure: Would mergeV/mergeE, in addition to your proposed extension method, solve your problem?

**Comment by evo-terren** [comment]
This library should probably just add support for mergeV/mergeE since those are native gremlin commands that basically do what I'm wanting natively. That being said, Cosmos Db doesn't support them, so I'm kind of out of luck. I'll close this for now since what I'm hoping for shouldn't be part of this library.

If you have the time, I'd still appreciate any guidance and/or documentation you can provide on how to add/update a vertex without all the properties (and side effect drop), whether that's through the `AsAdmin()` or whatever since I'm totally lost on how to use that functionality.
