### ISSUE TITLE
finding Mutual Friends

### ISSUE THREAD

**Issue by iAmBipinPaul** [ExRam/ExRam.Gremlinq#81]
Hi , Thanks again for  this awesome library.

Here is the raw Query in Gremlin to get mutual friends.

`g.V(FirstUserId).both("Friend").where(both("Friend").is(eq(SecondUserId)))`

The closest query I was able to write is below but it always return all the friends of first user as I was not able to write equivalent  statement  of `.is(eq(SecondUserId)`

```csharp
await _g.V(FirstUserId).Both<Friend>()
                   .Where(l => l.Both<Friend>().V(SecondUserId)).Dedup().OfType<User>();
```

Thank you 

reference links

1. https://groups.google.com/forum/#!topic/gremlin-users/Saw7hvOPrcM
2. https://stackoverflow.com/questions/36516914/get-a-list-of-common-friends-between-more-than-2-users-in-graph-database

**Comment by danielcweber** [comment]
Does the raw query work?

**Comment by iAmBipinPaul** [comment]
Hi , Yes it works I tried this raw query on azure portal.
is there option to execute the raw query using  `ExRam.Gremlinq` and Map result back to C# class type?

**Comment by danielcweber** [comment]
It can't work. It can't yield results. eq never takes a vertex id.

**Comment by iAmBipinPaul** [comment]
I tried this query on and Looks like it is working.
Here `UserFriendsWithUser` is my friend edge when a person becomes friends with other Person `(vertex)` I'm adding two edge there. 

A--`UserFriendsWithUser`-->B
B--`UserFriendsWithUser`-->A

![image](https://user-images.githubusercontent.com/9201481/85005316-547ea800-b178-11ea-9802-73ce9d04f646.png)

**Comment by danielcweber** [comment]
Not sure why it yields results. I am 100% sure  you can't insert a vertex id into is(eq(...)) ever. Why something is in scope anyway might be CosmosDB specific I don't know. Gremlinq will never produce that kind of query. Instead, you might want to go for something like this:

    await _g.V(FirstUserId).Both<Friend>()
                   .Where(__ => __.Both<Friend>().As((f, __) => __.V(SecondUserId).Where(s => s == f))).Dedup().OfType<User>();

**Comment by danielcweber** [comment]
You might have to tweak the query a bit.

**Comment by iAmBipinPaul** [comment]
Okay !
Thak you so much !
one more question , how can I execute `raw` query using `ExRam.Gremlinq` and Map result back to C# class type?

**Comment by danielcweber** [comment]
You can't. That's the whole point of ExRam.Gremlinq: Abstraction.

**Comment by iAmBipinPaul** [comment]
Okay !
I will try the query you have provide and will update about that here.
Than you !

**Comment by iAmBipinPaul** [comment]
Hi 
I tried the query you have suggested , I had to do little tweak as I was getting completion error.

Suggested one 
```csharp
await _g.V(FirstUserId).Both<Friend>()
               .Where(__ => __.Both<Friend>().As((f, __) => __.V(SecondUserId)
              .Where(s => s == f))).Dedup().OfType<User>();
```

I was able to write without any compilation error 

```csharp
  var mutualFriends = await _g.V(_marko.Id).Both<Knows>()
                .Where(__ => __.Both<Knows>())
                .As((f, __) => f.V(_peter.Id)
                    .Where(s => s == f).Dedup().OfType<Person>());
```

Relation (Know ) between User (People here )
```
marko <----> josh
marko <----> vadas
marko <----> daniel
marko <----> stefan

peter <----> vadas
peter <----> torrey
peter <----> josh
```

so When I run query to get friends (Know edge) between `marko` and `peter` I'm getting empty array but in fact it should return `vada` and `josh`

Here is the code I have prepared 
https://github.com/iAmBipinPaul/ExRam.Gremlinq.Issue.81

Thank you !

**Comment by danielcweber** [comment]
So what you actually want to do is to find friends of marko f1 and friends of peter f2 and determine those where f1 == f2 ?

```csharp
            var mutualFriends = await _g.V(_marko.Id).Both<Knows>()
                .As((__, f) => __.V(_peter.Id)
                    .Both<Knows>()
                    .OfType<Person>()
                    .Where(s => s == f).Dedup());
```

**Comment by danielcweber** [comment]
It would be cool if you could work this example into the samples project and open a PR, showcasing what it does and how it's done.

**Comment by danielcweber** [comment]
There's an even more elegant solution to this:

            var mutualFriends = await _g.V(_marko.Id)
                .Both<Knows>()
                .Fold()
                .As((__, markosFriends) => __.V(_peter.Id)
                    .Both<Knows>()
                    .OfType<Person>()
                    .Where(s => markosFriends.Value.Contains(s)).Dedup());

**Comment by iAmBipinPaul** [comment]
@danielcweber  
Thank you so much.
I will try this today and will open PR on sample repo.

**Comment by iAmBipinPaul** [comment]
Hi , Here is my pull request.
Thank you :) !
https://github.com/ExRam/ExRam.Gremlinq.Samples/pull/4

**Comment by iAmBipinPaul** [comment]
Hi , using this below query , I'm able to get mutual friends between Marko and Peter. But I need to get friends between
 `Marko` and `Peter` ,
 `Marko` and `josh` in one single query.

so here `Marko` will be constant and other User may be one or more than one.
```csharp
var mutualFriends = await _g.V(_marko.Id)
    .Both<Knows>()
    .OfType<Person>()
    .Fold()
    .As((__, markosFriends) => __.V(_peter.Id)
        .Both<Knows>()
        .OfType<Person>()
        .Where(petersFriend => markosFriends.Value.Contains(petersFriend)).Dedup());
```

Thank you :) !

**Comment by iAmBipinPaul** [comment]
Hi , I'm pretty new to this graph database.
I tried to find of example on web , I didn't found any example on the web that performs this query.

**Comment by danielcweber** [comment]
How about

````csharp
var mutualFriends = await _g.V(_marko.Id)
    .Both<Knows>()
    .OfType<Person>()
    .Fold()
    .As((__, markosFriends) => __.V(_peter.Id)
        .Both<Knows>()
        .OfType<Person>()
        .Where(petersFriend => markosFriends.Value.Contains(petersFriend))
        .Fold()
        .As((__, markosAndPetersFriends) => __.V(_josh.Id)
            .Both<Knows>()
            .OfType<Person>()
            .Where(joshsFriend => markosAndPetersFriends.Value.Contains(joshsFriend ))));
````
 A great place to start learning Gremlin is the [official documentation](http://tinkerpop.apache.org/docs/current/reference/#_tinkerpop_documentation). You need to be familiar with Gremlin concepts to make the most of ExRam.Gremlinq. The sample graph in ExRam.Gremlinq.Samples is directly taken from the offical docs.

**Comment by iAmBipinPaul** [comment]
Hi ,Thank you for all your effort.
I will go through the documentation.

I think the query you given here is to get mutual friend between `Marko` , `Peter` and `Jsoh`.
but what I want is  to get mutual friends between two users,

So here we can say `Marko` is fixed but I need get mutual friends between `Marko and  U1`, `Marko and U2` , `Marko and U3` , `Marko and U4`, .........`Marko and Un`.

I'm not sure whether this is possible to get in one query or not.

Thank you 👍

**Comment by danielcweber** [comment]
I'm not sure I understand...if one of the users is variable and only known at runtime, just insert that user's id whenever you create and execute the query.

**Comment by iAmBipinPaul** [comment]
Hi , sorry the way I explained  it was not clear.
so I want to find mutual friend between `Marko` and another `array of user  {U1,U3}`.
so it should return data like this.

`Marko` and `U1`  has 4 mutual friend (`U2`,`U3`, `U5`,`U6`)
`Marko` and `U3` has two mutual friend (`U1`, `U6` )

if we will use query like below ,  to get mutual friend between `Marko and U1`, have to make one database call , to get mutual friend between `Marko and U3` have to make another database call , so can we get this in one query.


```csharp
var mutualFriends = await _g.V(_marko.Id)
    .Both<Knows>()
    .OfType<Person>()
    .Fold()
    .As((__, markosFriends) => __.V(_peter.Id)
        .Both<Knows>()
        .OfType<Person>()
        .Where(petersFriend => markosFriends.Value.Contains(petersFriend)).Dedup());
```

**Comment by danielcweber** [comment]
Then more like....

````csharp
var mutualFriends = await _g.V(_marko.Id)
    .Both<Knows>()
    .OfType<Person>()
    .Fold()
    .As((__, markosFriends) => __.V(friend1.Id, friend2.Id)
        .Both<Knows>()
        .OfType<Person>()
        .Dedup()
        .Where(otherFriend => markosFriends.Value.Contains(otherFriend)));


?

**Comment by iAmBipinPaul** [comment]
Hi , Thank you !
I will try and will update about it here.

**Comment by iAmBipinPaul** [comment]
I tried this and it works. only one thing I'm not able to do here is mapping or write select query in proper way.

marko <--Knows--> josh
marko <--Knows--> vadas
marko <--Knows--> daniel
marko <--Knows--> stefan

peter <--Knows--> vadas
peter <--Knows--> torrey
peter <--Knows--> josh

torrey <--Knows--> stefan


```csharp

 object[] otherUserIds = new object[] { _peter.Id, _torrey.Id };

var mutualFriends = await _g.V(_marko.Id)
                .Both<Knows>()
                .OfType<Person>()
                .Fold()
                .As((__, markosFriends) => __.V(otherUserIds)
                    .Both<Knows>()
                    .OfType<Person>()
                    .Dedup()
                    .Where(otherFriend => markosFriends.Value.Contains(otherFriend)));
```

when running the above query it  returns.

`vadas`
`josh`
`stefan`

this result is totally fine but here I'm not able to know that `marko` and `peter` has two mutual friends ie (`vadas` ,`josh`) where as `mako` and  `torrey` has one mutual friend ie `stefan`.I'm expecting some tuple result here like.

peterId, , { `vadas` ,`josh`}
torreyId , {`stefan`}

Thank you for all your effort.

**Comment by danielcweber** [comment]
You can use projection:

````csharp
object[] otherUserIds = new object[] { _peter.Id, _torrey.Id };

var mutualFriends = await _g.V(_marko.Id)
    .Both<Knows>()
    .OfType<Person>()
    .Fold()
    .As((__, markosFriends) => __.V(otherUserIds)
        .Project(p => p
            .ToTuple()
                .By(__ => __)
                .By(__ => __
                    .Both<Knows>()
                    .OfType<Person>()
                    .Dedup()
                    .Where(otherFriend => markosFriends.Value.Contains(otherFriend))
                    .Fold())));

**Comment by iAmBipinPaul** [comment]
Hi , Thak you !
I will give a try , I will update you about this here.

**Comment by iAmBipinPaul** [comment]
Thank you  so much.
It is working  👍
