### ISSUE TITLE
Azure Functions

### ISSUE THREAD

**Issue by mike-kolback** [ExRam/ExRam.Gremlinq#84]
I am currently using CosmosDB within Azure Functions.  Dealing with the Gremlin.Net library has been rather painful so I've resorted to looking for alternatives and stumbled upon this library.  

My question is, theoretically can this library be leveraged within the Azure Functions Platform in .NET Core 3.0?

**Comment by danielcweber** [comment]
Sure. We've been doing that for years now.

**Comment by mike-kolback** [comment]
Great!

**Comment by mike-kolback** [comment]
Is there by chance a specific Functions version that is necessary?  I seem to be having some issues when running my functions locally, specifically around a reference to ```netstandard 2.1```

**Comment by danielcweber** [comment]
Nope. Make sure you're running on .NET Core 3.x.

**Comment by haseebahmed7** [comment]
@danielcweber I'm using .NET Core 3.1 and latest Azure Functions, I keep getting the following error: "Could not load file or assembly 'System.Interactive.Async, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The system cannot find the file specified.". I've even directly installed that package into my Azure Function.

**Comment by mike-kolback** [comment]
I downgraded Microsoft.NET.Sdk.Functions to version 3.0.3 and it works.  Must have been a breaking change at some point between 3.0.3 and 3.0.7.

@danielcweber any ideas on what the issue could be?

**Comment by haseebahmed7** [comment]
@mike-kolback That worked! You saved me from a lot of pain so Thank you! :-D

**Comment by haseebahmed7** [comment]
> I downgraded Microsoft.NET.Sdk.Functions to version 3.0.3 and it works. Must have been a breaking change at some point between 3.0.3 and 3.0.7.
> 
> @danielcweber any ideas on what the issue could be?

That worked! You saved me from a lot of pain so Thank you! :-D

**Comment by danielcweber** [comment]
Looks like a package downgrade for System.Interactive.Async...which is an error by default in .NET Core projects I think, but might also end up as just a warning. Have a look for "package downgrade" in the warnings during build.
