### ISSUE TITLE
Request Documentation 

### ISSUE THREAD

**Issue by NaanKaran** [ExRam/ExRam.Gremlinq#85]
Please provide Documentation for all extension.

Thanks in advance ..

**Comment by danielcweber** [comment]
Sure. When do you need it?

**Comment by NaanKaran** [comment]
Please take your own time. you done a great job. i really like this package. thanks for your effort.
once you upload the document please tag me.

**Comment by NaanKaran** [comment]
i need one help ..  i have a requirement as json below. how to travels to get the same format of data. 

My data like : 
Vertex and its Edges as like  - BU Head -> Manager -> Team Lead -> Worker


{
            "name": "BU Head",
            "children": [
              {
                  "name": "Manager A",
                  "children": [
                    {
                        "name": "Team Lead",
                         "children": []
                    },
                    {
                        "name": "Team Lead",
                        "children": []
                    }
                  ]
              },
              {
                  "name": "Manager B",
                  "children": [
                    {
                        "name": "Team Lead",
                        "children": [
                    {
                        "name": "Worker A",
                         "children": []
                    },
                    {
                        "name": "Worker B",
                        "children": []
                    }
                  ]
                    },
                    {
                        "name": "Team Lead",
                        "children": []
                    }
                  ]
              }
            ]
        }

**Comment by mike-kolback** [comment]
@danielcweber Is there documentation surrounding specific methods definitions (i.e. Both, Fold, Dedup, etc.) or is this Native Gremlin Terminology.  I am rather new to Gremlin and GremlinQ for that matter.  Trying to find the best resources to learn these methods.

**Comment by danielcweber** [comment]
http://tinkerpop.apache.org/docs/current/reference/#preface

**Comment by mike-kolback** [comment]
Thanks @danielcweber .  Looks like I have some reading to do.
