### ISSUE TITLE
Azure functions and v8.0.0-preview-0707 exception

### ISSUE THREAD

**Issue by Anton0123** [ExRam/ExRam.Gremlinq#87]
Using ExRam.Gremlinq.Core and ExRam.Gremlinq.Providers.CosmosDb 8.0.0-preview-0707 with Azure functions throws a `System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Interactive.Async, Version=4.1.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The system cannot find the file specified.'
`  when trying to interract with the graph.

Code: https://pastebin.com/mqMs2gAC

I created another project using a console application instead and the same code runs fine. Not sure if I've missed something or if it's a bug.

**Comment by danielcweber** [comment]
[This comment](https://github.com/ExRam/ExRam.Gremlinq/issues/84#issuecomment-648294011) from #84 seems to be a workaround.

**Comment by Anton0123** [comment]
> [This comment](https://github.com/ExRam/ExRam.Gremlinq/issues/84#issuecomment-648294011) from #84 seems to be a workaround.

That worked, thanks
