### ISSUE TITLE
Can anyone help me setup DI for cosmos

### ISSUE THREAD

**Issue by fergers** [ExRam/ExRam.Gremlinq#88]
I am trying to rewrite a big graph API project talking to cosmos from another dev company who uses raw queries to query the database. This package could really help us out taking the project to a higher level.

Because the lack of documentation I can't really figure out how I can setup/use the query builder to talk to the cosmos graph db.

Anyone has some useful samples?

**Comment by ChrisMissal** [comment]
What did you find @fergers ? Anything you can add to this to help future folks with the same question?

**Comment by fergers** [comment]
I didn't see that the preview packages where available for .net core to register DI. So After I did that it all worked like a charm.
