### ISSUE TITLE
Enable parameter logging

### ISSUE THREAD

**Issue by SyntaxUnknown** [ExRam/ExRam.Gremlinq#9]
For debugging purposes, it'd be nice if we could see parameters logged along with the query. 

I realize this is a possible security issue, so could we follow what Entity Framework does with EnableSensitiveDataLogging logging with their builder?

Maybe along with the .WithLogger() method, we could also add a .WithSensitiveData()? Or maybe a second parameter to .WithLogger(_logger, true)?

For your reference, here's how I implemented that logging in WebSocketGremlinQueryExecutor:

```
_logger?.LogTrace($"Executing Gremlin query {serialized.QueryString}" +
                $"{Environment.NewLine}{string.Join(Environment.NewLine, serialized.Bindings.Select(b => $"{b.Key}: {b.Value}").ToArray())}");
```

Thanks again!!

**Comment by danielcweber** [comment]
I actually have that requirement too but didn't implement it yet for the exact same reasons. What does EF consider sensitive data? Is it all the bindings? Or just select fields (like password columns etc.)?

Also, it would be even nicer to embed the bindings directly into the query, so it can be copy-pasted into e.g. CosmosDB data explorer to debug queries. But the embedding seems kind of a hack.

**Comment by SyntaxUnknown** [comment]
The flag in EF is an all or nothing setting, so if you enable it, it'll include the parameters along with the queries in the logging. I don't believe they give you any way to flag certain parameters as sensitive or anything like that.

I was thinking about logging the params in the queries, but it looked like it would get pretty ugly, especially when dealing with quotes and stuff like that.

**Comment by danielcweber** [comment]
Gremlinq will shift to bytecode in the 8.x release, where there is no distinction between the bytecode and parameters. There is still a notion of bindings but it won't be used. So unless the whole query is logged (which might or might not be a good idea), this issue is now more or less obsolete.

**Comment by danielcweber** [comment]
From the latest preview on (> 8.0.0-preview-0196), check out the [latest update of the samples](https://github.com/ExRam/ExRam.Gremlinq.Samples/blob/master/ExRam.Gremlinq.Samples/Program.cs#L46). Query/Parameter logging has been reworked and made more configurable.
