### ISSUE TITLE
"G" static variable does anot appear to have a ConfigureEnvironment variable

### ISSUE THREAD

**Issue by Darkenor1** [ExRam/ExRam.Gremlinq#90]
According to here:
https://github.com/ExRam/ExRam.Gremlinq.Samples/blob/main/ExRam.Gremlinq.Samples/Program.cs#L13

and here:
https://github.com/ExRam/ExRam.Gremlinq.Samples/blob/main/ExRam.Gremlinq.Samples/Program.cs#L35

I should be able to statically import the "g" variable as so:

```
using static ExRam.Gremlinq.Core.GremlinQuerySource;

namespace Database
{
    public class GremlinDBIO
    {
        public static string Hostname = "REDACTED";
        public static int Port = 443;
        public static string AuthKey = "REDACTED";
        public static string DatabaseName = "REDACTED";
        public static string Collection = "REDACTED";


        public GremlinDBIO()
        {
            var _g = g
                .ConfigureEnvironment(env => env
                    .UseLogger(logger)
                    //Since the Vertex and Edge classes contained in this sample implement IVertex resp. IEdge,
                    //setting a model is actually not required as long as these classes are discoverable (i.e. they reside
                    //in a currently loaded assembly). We explicitly set a model here anyway.
                    .UseModel(GraphModel
                        .FromBaseTypes<Vertex, Edge>(lookup => lookup
                            .IncludeAssembliesOfBaseTypes())
                        //For CosmosDB, we exclude the 'PartitionKey' property from being included in updates.
                        .ConfigureProperties(model => model
                            .ConfigureElement<Vertex>(conf => conf
                                .IgnoreOnUpdate(x => x.PartitionKey)))).UseCosmosDb(builder => builder
                        .At(uri, databaseName, graphName)
                        .AuthenticateBy(authKey)
                        .ConfigureWebSocket(builder => builder
                            //Disable query logging for a noise free console output.
                            //Enable logging by setting the verbosity to anything but None.
                            .ConfigureQueryLoggingOptions(o => o
                                .SetQueryLoggingVerbosity(QueryLoggingVerbosity.None)))));

        }

    }
}
```
However, when I do so on vscode with .net standard 2.1 I receive this error:

error CS1061: 'IConfigurableGremlinQuerySource' does not contain a definition for 'ConfigureEnvironment' and no accessible extension method 'ConfigureEnvironment' accepting a first argument of type 'IConfigurableGremlinQuerySource' could be found (are you missing a using directive or an assembly reference?) 

Am I missing something in how to use this? Is this a Linux issue? I'm running on Ubuntu, VSCode, .NET standard 2.1

**Comment by danielcweber** [comment]
Hard to tell without a complete project structure.

**Comment by Darkenor1** [comment]
One can reproduce it by cloning the sample project on Ubuntu and VSCode, adding GremlinQ as follows:

cd ExRam.Gremlinq.Samples/
dotnet add package Exram.Gremlinq
dotnet add package Exram.Gremlinq.Core
dotnet add package Exram.Gremlinq.Providers
dotnet add package Exram.Gremlinq.Providers.WebSocket

Then just build and you'll see the error.

**Comment by danielcweber** [comment]
Look,

I specifically ask for a complete minimal executable repro project for a reason: To get insight into the actual Gremlinq version you're using and to get an idea about the target framework you're building agains, among other things. All of these things are information you did not bother to provide. Yet you expect me to invest the time to setup a fresh project to reproduce the error you're experiencing, which I cannot.

The sample project on the main branch (550edbd7cca782d8f8e2ffd159dd7b1d2272cb59) builds just fine.
