### ISSUE TITLE
Sample Project Does not Build

### ISSUE THREAD

**Issue by Blorgazor** [ExRam/ExRam.Gremlinq#91]
**Describe the bug**
I am attempting to build the sample project using Ubuntu, VSCode, .NET Core 3.1. It does not.
Sample Error:

Program.cs(36,18): error CS1061: 'IConfigurableGremlinQuerySource' does not contain a definition for 'ConfigureEnvironment' and no accessible extension method 'ConfigureEnvironment' accepting a first argument of type 'IConfigurableGremlinQuerySource' could be found (are you missing a using directive or an assembly reference?) 

**Expected behavior**
The project builds.

**Version information**
<PackageReference Include="Exram.Gremlinq.Core" Version="7.0.6" />
<PackageReference Include="Exram.Gremlinq.Providers" Version="7.0.6" />
<PackageReference Include="Exram.Gremlinq.Providers.WebSocket" Version="7.0.6" />

**Minimal working example**
You **MUST** provide one of the following

GitHub Repo:
https://github.com/Darkenor1/ExRam.Gremlinq.Samples
(Fork of samples with sln removed, dotnet core packages added)

**Additional context**
If the problem is PBKAC, I am more than happy to provide documentation to the README regarding steps on how to do it for those of us running linux/vscode.

**Comment by danielcweber** [comment]
The samples reference ExRam.Gremlinq 8.x-previews. Why would you manually add the 7.x versions? Of course the older version doesn't have all the methods that the samples use.

**Comment by Darkenor1** [comment]
I updated it to preview-8 and it worked. There isn't a compatible vscode project that builds out of the box in the samples project, so I had to add the packages manually. My build steps were just:

Clone
dotnet add package Exram.Gremlinq.Core
dotnet add package Exram.Gremlinq.Providers
dotnet add package Exram.Gremlinq
build

Is there a reason the preview version is in the sample project? Shouldn't it be the current stable version?

**Comment by danielcweber** [comment]
>Is there a reason the preview version is in the sample project? Shouldn't it be the current stable version?

7.x is boring. Preview is new. New is good ;-)

**Comment by danielcweber** [comment]
Seriour answer to that: I can't and won't provide any help for 7.x stuff - there's just no resources. So if I want to get something useful from this and the people using the library (e.g. bug reports etc) for my own development, then it has to be the current preview.

**Comment by Blorgazor** [comment]
ok fair enough! Closing ticket and thank you.
