### ISSUE TITLE
String lamda on .Where()

### ISSUE THREAD

**Issue by jurkrit** [ExRam/ExRam.Gremlinq#92]
Could you please provide me an example of how to use the string lamda on the Where

An example for: G.V().OfType<X>().Where(x => x.Name == '123');

**Comment by danielcweber** [comment]
https://github.com/ExRam/ExRam.Gremlinq/blob/a360da786d97435fbff7fef26897b92746b6072c/ExRam.Gremlinq.Core.Tests/QueryExecutionTest.cs#L945

**Comment by danielcweber** [comment]
That's because CosmosDB doesn't support any lambdas.

**Comment by jurkrit** [comment]
Awesome thanks for your help, reflection to the rescue
