### ISSUE TITLE
Why not include the feature :mgmt = graph.openManagement()

### ISSUE THREAD

**Issue by ChenZhaobin** [ExRam/ExRam.Gremlinq#93]
I find that in JanusGraph.Java we can use mgmt = graph.openManagement() to manage the schemas,
do we have similar functions in this project?

**Comment by ChenZhaobin** [comment]
and this one : graph.tx().commit()

**Comment by danielcweber** [comment]
I'm afraid no.

**Comment by danielcweber** [comment]
Closing: unfortunately the feature doesn't exist and is outside the scope of Gremlinq for the time being.
