### ISSUE TITLE
How I can get graph tree

### ISSUE THREAD

**Issue by jayaemekar** [ExRam/ExRam.Gremlinq#933]
I wanted to get all the vertex and edge properties for graph tree with  all out edges.

From startvertex I want to traverse through all the outgoing edges, till the level it has outgoing edge, and return all the vertex and edge property. for each level

**Comment by danielcweber** [comment]
Close in favour of #934 ?

**Comment by danielcweber** [comment]
The Tree-operator has been added in Gremlinq 12.13.0.
