### ISSUE TITLE
Drop Vertex by property asynchronously

### ISSUE THREAD

**Issue by ederflo** [ExRam/ExRam.Gremlinq#94]
How can i drop a vertex by a given property? 

My approach: await _g.V<T>().Where(predicate).Drop().FirstAsync();

**Comment by danielcweber** [comment]
Looks about right.

**Comment by ederflo** [comment]
My errormessage: The expression 'x.pKey.Equals(value(ArduviData.DataAccess.SupplierVertexAccess+<>c__DisplayClass4_0).pKey)' is not supported. 

I try to delete all Verteces containing this pertition key.

**Comment by ederflo** [comment]
Finally i fixed it.
It works if i execute it with 'FirstOrDefaultAsync()'

Is there an opportunity to execute it without expecting any response?

**Comment by danielcweber** [comment]
You'll always get a response. However, if you omit any "First...." completely, you can still await the query and ignore the result (which will be the same as with "ToArrayAsync()").

**Comment by ederflo** [comment]
But in that case, it returns null..

**Comment by danielcweber** [comment]
drop() doesn't leave any results...

https://tinkerpop.apache.org/docs/current/reference/#drop-step
